'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { FiArrowLeft, FiAward, FiBarChart2, FiCheckCircle, FiEdit3, FiLock, FiPlus, FiRefreshCw, FiSettings, FiTarget, FiTrash2, FiUsers, FiX } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Category={id:string;kpi_role_id:string;name:string;weight:number;sort_order:number};
type Template={id:string;kpi_role_id:string;category_id:string|null;code:string;name:string;formula_type:string;target_value:number;unit:string;item_weight:number|null;evidence_required:boolean;sort_order:number};
type KpiRole={id:string;key:string;name:string;scoring_model:'staff_equal'|'category_weighted';description:string|null;categories:Category[];templates:Template[]};
type Period={id:string;name:string;start_date:string;end_date:string;status:'draft'|'open'|'review'|'locked'};
type Member={id:string;name:string;email:string};
type Assignment={id:string;period_id:string;membership_id:string;member_name:string;kpi_role_id:string;role_name:string;scoring_model:string;reviewer_membership_id:string|null;status:string;final_score:number|null;raw_score:number|null;coverage:number|null;score_status:string|null;updated_at:string};
type Result={id:string;assignment_id:string;code:string;name:string;category_name:string|null;formula_type:string;target_value:number;unit:string;evidence_required:boolean;is_applicable:boolean;actual_value:number|null;evidence_url:string|null;note:string|null;raw_achievement:number|null;score:number|null;reviewer_score:number|null;review_note:string|null};
type Modal='role'|'category'|'template'|'period'|'assignment'|'result'|null;

const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const monthEnd=()=>{const d=new Date(`${today()}T12:00:00`);return new Date(d.getFullYear(),d.getMonth()+1,0).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});};
const score=(value:number|null)=>value==null?'—':`${Number(value).toFixed(1)}%`;
const formulas:Record<string,string>={higher_better:'Semakin tinggi semakin baik',lower_better:'Semakin rendah semakin baik',percentage:'Persentase',derived_ratio:'Rasio turunan',compliance:'Compliance / SLA',binary:'Ya / Tidak',milestone_progress:'Progress milestone'};

export default function KpiManagementPage(){
  const [state,setState]=useState<'loading'|'ready'|'denied'>('loading');
  const [permissions,setPermissions]=useState<string[]>([]);const [membershipId,setMembershipId]=useState('');
  const [roles,setRoles]=useState<KpiRole[]>([]);const [periods,setPeriods]=useState<Period[]>([]);const [members,setMembers]=useState<Member[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);
  const [selected,setSelected]=useState<Assignment|null>(null);const [results,setResults]=useState<Result[]>([]);const [periodFilter,setPeriodFilter]=useState('');const [modal,setModal]=useState<Modal>(null);
  const [roleForm,setRoleForm]=useState({id:'',name:'',description:'',scoring_model:'staff_equal'});const [categoryForm,setCategoryForm]=useState({id:'',kpi_role_id:'',name:'',weight:'35',sort_order:'10'});
  const [templateForm,setTemplateForm]=useState({id:'',kpi_role_id:'',category_id:'',code:'',name:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,sort_order:'100'});
  const [periodForm,setPeriodForm]=useState({id:'',name:'',start_date:today().slice(0,8)+'01',end_date:monthEnd(),status:'open'});const [assignmentForm,setAssignmentForm]=useState({membership_id:'',period_id:'',kpi_role_id:'',reviewer_membership_id:''});
  const [resultForm,setResultForm]=useState<Result|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');

  async function load(){setError('');const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/ruang-kawan/');return;}const [accessR,memberR,workspaceR]=await Promise.all([supabase.rpc('get_my_access'),supabase.rpc('current_membership_id'),supabase.rpc('list_kpi_workspace')]);const access=Array.isArray(accessR.data)?accessR.data[0]:accessR.data;if(!access?.permissions?.includes('kpi.view_self')){setState('denied');return;}if(workspaceR.error){setError('KPI Management belum dapat dimuat. Pastikan migrasi database sudah diterapkan.');setState('ready');return;}const data=workspaceR.data as {roles:KpiRole[];periods:Period[];members:Member[];assignments:Assignment[]};setPermissions(access.permissions??[]);setMembershipId(memberR.data as string);setRoles(data.roles??[]);setPeriods(data.periods??[]);setMembers(data.members??[]);setAssignments(data.assignments??[]);setPeriodFilter(value=>value||data.periods?.[0]?.id||'');setState('ready');if(selected){const fresh=data.assignments?.find(item=>item.id===selected.id);if(fresh)setSelected(fresh);}}
  useEffect(()=>{void load();},[]);
  async function refreshResults(assignmentId:string){const response=await createClient().rpc('list_kpi_results',{target_assignment_id:assignmentId});if(response.error){setError(response.error.message);return;}setResults((response.data??[]) as Result[]);}
  async function openAssignment(item:Assignment){setSelected(item);await refreshResults(item.id);}
  const filtered=useMemo(()=>assignments.filter(item=>!periodFilter||item.period_id===periodFilter),[assignments,periodFilter]);const activeRole=roles.find(role=>role.id===templateForm.kpi_role_id);const canManage=permissions.includes('kpi.manage');const canReview=permissions.includes('kpi.review');
  const stats={people:filtered.length,onTrack:filtered.filter(a=>(a.final_score??0)>=80).length,attention:filtered.filter(a=>a.final_score!=null&&a.final_score<80).length,locked:filtered.filter(a=>a.status==='locked').length};
  function show(type:Modal){setError('');if(type==='role')setRoleForm({id:'',name:'',description:'',scoring_model:'staff_equal'});if(type==='category')setCategoryForm({id:'',kpi_role_id:roles.find(r=>r.scoring_model==='category_weighted')?.id??roles[0]?.id??'',name:'',weight:'35',sort_order:'10'});if(type==='template')setTemplateForm({id:'',kpi_role_id:roles[0]?.id??'',category_id:'',code:'',name:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,sort_order:'100'});if(type==='period')setPeriodForm({id:'',name:'',start_date:today().slice(0,8)+'01',end_date:monthEnd(),status:'open'});if(type==='assignment')setAssignmentForm({membership_id:members[0]?.id??'',period_id:periods.find(p=>p.status!=='locked')?.id??'',kpi_role_id:roles[0]?.id??'',reviewer_membership_id:''});setModal(type);}
  function editRole(role:KpiRole){setRoleForm({id:role.id,name:role.name,description:role.description??'',scoring_model:role.scoring_model});setModal('role');}
  function editCategory(category:Category){setCategoryForm({id:category.id,kpi_role_id:category.kpi_role_id,name:category.name,weight:String(category.weight),sort_order:String(category.sort_order)});setModal('category');}
  function editTemplate(template:Template){setTemplateForm({id:template.id,kpi_role_id:template.kpi_role_id,category_id:template.category_id??'',code:template.code,name:template.name,formula_type:template.formula_type,target_value:String(template.target_value),unit:template.unit,item_weight:template.item_weight==null?'':String(template.item_weight),evidence_required:template.evidence_required,sort_order:String(template.sort_order)});setModal('template');}
  function editPeriod(period:Period){setPeriodForm({id:period.id,name:period.name,start_date:period.start_date,end_date:period.end_date,status:period.status});setModal('period');}
  async function rpc(name:string,args:Record<string,unknown>){setSaving(true);setError('');const response=await createClient().rpc(name,args);setSaving(false);if(response.error){setError(response.error.message);return false;}setModal(null);setMessage('Perubahan KPI berhasil disimpan.');await load();return true;}
  function saveRole(e:FormEvent){e.preventDefault();void rpc('save_kpi_role',{role_id:roleForm.id||null,payload:roleForm});}function saveCategory(e:FormEvent){e.preventDefault();void rpc('save_kpi_category',{category_id:categoryForm.id||null,payload:categoryForm});}function saveTemplate(e:FormEvent){e.preventDefault();void rpc('save_kpi_template',{template_id:templateForm.id||null,payload:templateForm});}function savePeriod(e:FormEvent){e.preventDefault();void rpc('save_kpi_period',{period_id:periodForm.id||null,payload:periodForm});}function saveAssignment(e:FormEvent){e.preventDefault();void rpc('assign_kpi',{assignment_id:null,payload:assignmentForm});}
  async function saveResult(e:FormEvent){e.preventDefault();if(!resultForm)return;const ok=await rpc('save_kpi_result',{result_id:resultForm.id,payload:{actual_value:resultForm.actual_value??'',evidence_url:resultForm.evidence_url??'',note:resultForm.note??'',is_applicable:resultForm.is_applicable,reviewer_score:resultForm.reviewer_score??'',review_note:resultForm.review_note??''}});if(ok&&selected)await refreshResults(selected.id);}
  async function submit(status:'submitted'|'reviewed'){if(!selected)return;await rpc('set_kpi_assignment_status',{target_assignment_id:selected.id,new_status:status});}
  async function archive(type:'role'|'category'|'template',id:string,label:string){if(!window.confirm(`Nonaktifkan ${label}? Riwayat assignment lama tetap tersimpan.`))return;await rpc('archive_kpi_config',{config_type:type,target_id:id});}
  if(state==='loading')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><p>Menyiapkan KPI Management...</p></section></main>;
  if(state==='denied')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><h1>KPI Management belum tersedia</h1><p>Kamu belum memiliki izin KPI.</p><Link href="/ruang-kawan/dashboard/">Kembali</Link></section></main>;
  return <main className="rk-kpi-foundation"><section className="rk-kpi-shell">
    <nav className="rk-kpi-nav"><Link href="/ruang-kawan/dashboard/"><FiArrowLeft/> Dashboard</Link><button onClick={()=>void load()}><FiRefreshCw/> Muat ulang</button></nav>
    <header className="rk-kpi-heading"><div><small>Performance workspace</small><h1>KPI Management</h1><p>OKR → KPI role → realisasi & bukti → review → nilai final.</p></div>{canManage?<div><button onClick={()=>show('assignment')}><FiUsers/> Assign KPI</button><button onClick={()=>show('role')}><FiPlus/> Role baru</button></div>:null}</header>
    <section className="rk-kpi-stats"><article><FiUsers/><span><strong>{stats.people}</strong><small>Assignment</small></span></article><article><FiCheckCircle/><span><strong>{stats.onTrack}</strong><small>On Track</small></span></article><article data-alert={stats.attention>0}><FiTarget/><span><strong>{stats.attention}</strong><small>Perlu perhatian</small></span></article><article><FiLock/><span><strong>{stats.locked}</strong><small>Terkunci</small></span></article></section>
    <section className="rk-kpi-toolbar"><label>Periode<select value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)}><option value="">Semua periode</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} · {p.status}</option>)}</select></label>{canManage?<div><button onClick={()=>show('period')}><FiPlus/> Periode</button><button onClick={()=>show('category')}><FiBarChart2/> Kategori</button><button onClick={()=>show('template')}><FiSettings/> Item KPI</button></div>:null}</section>
    {message?<p className="rk-kpi-alert">{message}</p>:null}{error?<p className="rk-kpi-alert" data-error>{error}</p>:null}
    <section className="rk-kpi-layout"><div className="rk-kpi-list">{filtered.map(item=><button key={item.id} data-active={selected?.id===item.id} onClick={()=>void openAssignment(item)}><span data-score={item.score_status}>{score(item.final_score)}</span><div><small>{item.role_name}</small><strong>{item.member_name}</strong><p>{item.score_status||'Belum Dinilai'} · coverage {score(item.coverage)}</p></div></button>)}{!filtered.length?<p className="rk-kpi-empty">Belum ada assignment pada periode ini.</p>:null}</div>
      <div className="rk-kpi-workspace">{selected?<><header><div><small>{selected.role_name}</small><h2>{selected.member_name}</h2><p>Nilai final <b>{score(selected.final_score)}</b> · capaian mentah {score(selected.raw_score)} · coverage {score(selected.coverage)}</p></div><em data-status={selected.score_status}>{selected.score_status||'Belum Dinilai'}</em></header>
        {selected.scoring_model==='category_weighted'?<section className="rk-kpi-formula"><strong>C-Level</strong><span>Activity 35%</span><span>Output 35%</span><span>Impact 30%</span></section>:<section className="rk-kpi-formula"><strong>Staf</strong><span>Rata-rata seluruh KPI aktif</span><span>Skor reguler maks. 100%</span></section>}
        <div className="rk-kpi-results">{results.map(item=><button key={item.id} onClick={()=>{setResultForm(item);setModal('result');}}><div><small>{item.category_name||item.code} · {formulas[item.formula_type]}</small><strong>{item.name}</strong><p>Target {item.target_value} {item.unit}{item.evidence_required?' · evidence wajib':''}</p></div><span><b>{score(item.reviewer_score??item.score)}</b><small>Aktual {item.actual_value??'—'} · raw {score(item.raw_achievement)}</small></span><FiEdit3/></button>)}</div>
        <footer>{selected.membership_id===membershipId&&selected.status==='active'?<button onClick={()=>void submit('submitted')}><FiCheckCircle/> Ajukan review</button>:null}{(canReview||selected.reviewer_membership_id===membershipId)&&selected.status==='submitted'?<button onClick={()=>void submit('reviewed')}><FiAward/> Selesaikan review</button>:null}</footer>
      </>:<div className="rk-kpi-select-empty"><FiTarget/><h2>Pilih assignment KPI</h2><p>Detail realisasi, bukti, rumus, dan hasil review akan tampil di sini.</p></div>}</div>
    </section>
    {canManage?<section className="rk-kpi-config"><header><div><FiSettings/><span><small>Admin configuration</small><h2>Role dan template KPI</h2></span></div><p>Perubahan template hanya berlaku untuk assignment baru.</p></header><div>{roles.map(role=><article key={role.id}><header><div><strong>{role.name}</strong><small>{role.scoring_model==='category_weighted'?'Kategori berbobot':'Rata-rata KPI aktif'} · {role.templates.length} item</small></div><span><button onClick={()=>editRole(role)} aria-label={`Edit ${role.name}`}><FiEdit3/></button><button onClick={()=>void archive('role',role.id,role.name)} aria-label={`Nonaktifkan ${role.name}`}><FiTrash2/></button></span></header>{role.categories.length?<div className="rk-kpi-config-categories">{role.categories.map(category=><div key={category.id}><button onClick={()=>editCategory(category)}>{category.name} <b>{category.weight}%</b></button><button onClick={()=>void archive('category',category.id,category.name)} aria-label={`Nonaktifkan ${category.name}`}><FiTrash2/></button></div>)}</div>:null}<div className="rk-kpi-config-items">{role.templates.map(template=><div key={template.id}><button onClick={()=>editTemplate(template)}><span>{template.code}</span><strong>{template.name}</strong><small>{template.target_value} {template.unit}</small></button><button onClick={()=>void archive('template',template.id,template.name)} aria-label={`Nonaktifkan ${template.name}`}><FiTrash2/></button></div>)}{!role.templates.length?<p>Belum ada item KPI. Tambahkan item sebelum role di-assign.</p>:null}</div></article>)}</div><footer><strong>Periode</strong>{periods.map(period=><button key={period.id} onClick={()=>editPeriod(period)}>{period.name} · {period.status}</button>)}</footer></section>:null}
  </section>
  {modal?<div className="rk-kpi-modal"><form onSubmit={modal==='role'?saveRole:modal==='category'?saveCategory:modal==='template'?saveTemplate:modal==='period'?savePeriod:modal==='assignment'?saveAssignment:saveResult}><header><div><small>Konfigurasi KPI</small><h2>{modal==='role'?'KPI Role baru':modal==='category'?'Kategori berbobot':modal==='template'?'Item KPI':modal==='period'?'Periode KPI':modal==='assignment'?'Assign KPI':resultForm?.name}</h2></div><button type="button" onClick={()=>setModal(null)}><FiX/></button></header><div className="rk-kpi-form">
    {modal==='role'?<><label>Nama role<input value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})} required/></label><label>Model penilaian<select value={roleForm.scoring_model} onChange={e=>setRoleForm({...roleForm,scoring_model:e.target.value})}><option value="staff_equal">Staf · rata-rata KPI aktif</option><option value="category_weighted">C-Level · kategori berbobot</option></select></label><label className="wide">Deskripsi<textarea value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})}/></label></>:null}
    {modal==='category'?<><label>Role<select value={categoryForm.kpi_role_id} onChange={e=>setCategoryForm({...categoryForm,kpi_role_id:e.target.value})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Nama<input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} required/></label><label>Bobot (%)<input type="number" min="0.01" max="100" step="0.01" value={categoryForm.weight} onChange={e=>setCategoryForm({...categoryForm,weight:e.target.value})} required/></label></>:null}
    {modal==='template'?<><label>Role<select value={templateForm.kpi_role_id} onChange={e=>setTemplateForm({...templateForm,kpi_role_id:e.target.value,category_id:''})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{activeRole?.scoring_model==='category_weighted'?<label>Kategori<select value={templateForm.category_id} onChange={e=>setTemplateForm({...templateForm,category_id:e.target.value})} required><option value="">Pilih kategori</option>{activeRole.categories.map(c=><option key={c.id} value={c.id}>{c.name} · {c.weight}%</option>)}</select></label>:null}<label>Kode<input value={templateForm.code} onChange={e=>setTemplateForm({...templateForm,code:e.target.value})} required/></label><label className="wide">Nama KPI<input value={templateForm.name} onChange={e=>setTemplateForm({...templateForm,name:e.target.value})} required/></label><label>Rumus<select value={templateForm.formula_type} onChange={e=>setTemplateForm({...templateForm,formula_type:e.target.value})}>{Object.entries(formulas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Target<input type="number" step="0.0001" value={templateForm.target_value} onChange={e=>setTemplateForm({...templateForm,target_value:e.target.value})} required/></label><label>Satuan<input value={templateForm.unit} onChange={e=>setTemplateForm({...templateForm,unit:e.target.value})} required/></label><label><input type="checkbox" checked={templateForm.evidence_required} onChange={e=>setTemplateForm({...templateForm,evidence_required:e.target.checked})}/> Evidence wajib</label></>:null}
    {modal==='period'?<><label>Nama periode<input value={periodForm.name} onChange={e=>setPeriodForm({...periodForm,name:e.target.value})} placeholder="Agustus 2026" required/></label><label>Mulai<input type="date" value={periodForm.start_date} onChange={e=>setPeriodForm({...periodForm,start_date:e.target.value})} required/></label><label>Selesai<input type="date" value={periodForm.end_date} onChange={e=>setPeriodForm({...periodForm,end_date:e.target.value})} required/></label><label>Status<select value={periodForm.status} onChange={e=>setPeriodForm({...periodForm,status:e.target.value})}><option value="draft">Draft</option><option value="open">Open</option><option value="review">Review</option><option value="locked">Locked</option></select></label></>:null}
    {modal==='assignment'?<><label>Anggota<select value={assignmentForm.membership_id} onChange={e=>setAssignmentForm({...assignmentForm,membership_id:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Periode<select value={assignmentForm.period_id} onChange={e=>setAssignmentForm({...assignmentForm,period_id:e.target.value})}>{periods.filter(p=>p.status!=='locked').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Role KPI<select value={assignmentForm.kpi_role_id} onChange={e=>setAssignmentForm({...assignmentForm,kpi_role_id:e.target.value})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Reviewer<select value={assignmentForm.reviewer_membership_id} onChange={e=>setAssignmentForm({...assignmentForm,reviewer_membership_id:e.target.value})}><option value="">Belum ditentukan</option>{members.filter(m=>m.id!==assignmentForm.membership_id).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></>:null}
    {modal==='result'&&resultForm?<><label>Aktual<input type="number" step="0.0001" value={resultForm.actual_value??''} onChange={e=>setResultForm({...resultForm,actual_value:e.target.value===''?null:Number(e.target.value)})}/></label><label>Evidence URL<input type="url" value={resultForm.evidence_url??''} onChange={e=>setResultForm({...resultForm,evidence_url:e.target.value})} required={resultForm.evidence_required&&resultForm.is_applicable}/></label><label className="wide">Catatan<textarea value={resultForm.note??''} onChange={e=>setResultForm({...resultForm,note:e.target.value})}/></label><label><input type="checkbox" checked={resultForm.is_applicable} onChange={e=>setResultForm({...resultForm,is_applicable:e.target.checked})}/> KPI berlaku</label>{canReview||selected?.reviewer_membership_id===membershipId?<><label>Nilai reviewer<input type="number" min="0" max="100" step="0.01" value={resultForm.reviewer_score??''} onChange={e=>setResultForm({...resultForm,reviewer_score:e.target.value===''?null:Number(e.target.value)})}/></label><label className="wide">Catatan review<textarea value={resultForm.review_note??''} onChange={e=>setResultForm({...resultForm,review_note:e.target.value})}/></label></>:null}</>:null}
    </div>{error?<p className="rk-kpi-modal-error">{error}</p>:null}<footer><button type="button" onClick={()=>setModal(null)}>Batal</button><button data-primary disabled={saving}>{saving?'Menyimpan...':'Simpan'}</button></footer></form></div>:null}
  </main>;
}
