'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { FiArrowLeft, FiAward, FiBarChart2, FiCalendar, FiCheckCircle, FiEdit3, FiGrid, FiList, FiPlus, FiRefreshCw, FiRotateCcw, FiSettings, FiTarget, FiTrash2, FiUsers, FiX } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Category={id:string;kpi_role_id:string;name:string;weight:number;sort_order:number};
type Template={id:string;kpi_role_id:string;category_id:string|null;code:string;name:string;formula_type:string;target_value:number;unit:string;item_weight:number|null;evidence_required:boolean;aggregation_method:'sum'|'average'|'latest';sort_order:number};
type KpiRole={id:string;key:string;name:string;scoring_model:'staff_equal'|'category_weighted';description:string|null;categories:Category[];templates:Template[]};
type Period={id:string;name:string;start_date:string;end_date:string;status:'draft'|'open'|'review'|'locked'};
type Member={id:string;name:string;email:string};
type Assignment={id:string;period_id:string;membership_id:string;member_name:string;kpi_role_id:string;role_name:string;scoring_model:string;reviewer_membership_id:string|null;status:'active'|'submitted'|'revision_requested'|'reviewed'|'locked'|'cancelled';review_note?:string|null;final_score:number|null;raw_score:number|null;coverage:number|null;score_status:string|null;updated_at:string};
type Result={id:string;assignment_id:string;code:string;name:string;category_id:string|null;category_name:string|null;formula_type:string;target_value:number;unit:string;evidence_required:boolean;aggregation_method:'sum'|'average'|'latest';is_applicable:boolean;actual_value:number|null;evidence_url:string|null;note:string|null;raw_achievement:number|null;score:number|null;reviewer_score:number|null;review_note:string|null};
type Week={week_start:string;week_end:string;label:string};
type WeeklyUpdate={id:string;result_id:string;week_start:string;week_end:string;actual_value:number|null;evidence_url:string|null;progress:string|null;problem:string|null;plan:string|null;priority:string|null;justification:string|null};
type AccessRow={role_key:string;role_name:string;permissions:string[]};
type PeriodImpact={period_id:string;period_name:string;assignment_count:number;result_count:number;weekly_update_count:number;evidence_count:number};
type AssignmentImpact={assignment_id:string;member_name:string;role_name:string;period_name:string;result_count:number;weekly_update_count:number;evidence_count:number};
type Modal='role'|'category'|'template'|'period'|'periodDelete'|'assignment'|'assignmentDelete'|'result'|'weekly'|'personal'|null;
type WorkspaceMode='mine'|'review'|'setup';

const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const monthEnd=()=>{const d=new Date(`${today()}T12:00:00`);return new Date(d.getFullYear(),d.getMonth()+1,0).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});};
const score=(value:number|null)=>value==null?'—':`${Number(value).toFixed(1)}%`;
const formulas:Record<string,string>={higher_better:'Semakin tinggi semakin baik',lower_better:'Semakin rendah semakin baik',percentage:'Persentase',derived_ratio:'Rasio turunan',compliance:'Compliance / SLA',binary:'Ya / Tidak',milestone_progress:'Progress milestone'};
const aggregations:Record<string,string>={sum:'Jumlah seluruh minggu',average:'Rata-rata mingguan',latest:'Nilai minggu terakhir'};
const statusLabels:Record<string,string>={active:'Aktif',submitted:'Menunggu Review',revision_requested:'Perlu Revisi',reviewed:'Disetujui',locked:'Terkunci',cancelled:'Dibatalkan'};

export default function KpiManagementPage(){
  const [state,setState]=useState<'loading'|'ready'|'denied'>('loading');
  const [permissions,setPermissions]=useState<string[]>([]);const [membershipId,setMembershipId]=useState('');
  const [roles,setRoles]=useState<KpiRole[]>([]);const [periods,setPeriods]=useState<Period[]>([]);const [members,setMembers]=useState<Member[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [accessMatrix,setAccessMatrix]=useState<AccessRow[]>([]);
  const [selected,setSelected]=useState<Assignment|null>(null);const [results,setResults]=useState<Result[]>([]);const [weeks,setWeeks]=useState<Week[]>([]);const [updates,setUpdates]=useState<WeeklyUpdate[]>([]);
  const [periodFilter,setPeriodFilter]=useState('');const [view,setView]=useState<'card'|'list'>('card');const [mode,setMode]=useState<WorkspaceMode>('mine');const [modal,setModal]=useState<Modal>(null);
  const [roleForm,setRoleForm]=useState({id:'',name:'',description:'',scoring_model:'staff_equal'});const [categoryForm,setCategoryForm]=useState({id:'',kpi_role_id:'',name:'',weight:'35',sort_order:'10'});
  const [templateForm,setTemplateForm]=useState({id:'',kpi_role_id:'',category_id:'',code:'',name:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,aggregation_method:'sum',sort_order:'100'});
  const [periodForm,setPeriodForm]=useState({id:'',name:'',start_date:today().slice(0,8)+'01',end_date:monthEnd(),status:'open'});const [assignmentForm,setAssignmentForm]=useState({membership_id:'',period_id:'',kpi_role_id:'',reviewer_membership_id:''});
  const [periodImpact,setPeriodImpact]=useState<PeriodImpact|null>(null);const [deleteConfirmation,setDeleteConfirmation]=useState('');
  const [assignmentEditId,setAssignmentEditId]=useState('');const [assignmentImpact,setAssignmentImpact]=useState<AssignmentImpact|null>(null);const [assignmentDeleteConfirmation,setAssignmentDeleteConfirmation]=useState('');
  const [resultForm,setResultForm]=useState<Result|null>(null);const [weeklyForm,setWeeklyForm]=useState({result_id:'',week_start:'',week_end:'',actual_value:'',evidence_url:'',progress:'',problem:'',plan:'',priority:'',justification:''});
  const [personalForm,setPersonalForm]=useState({name:'',category_id:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,aggregation_method:'sum'});
  const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');

  const canManage=permissions.includes('kpi.manage');const canReview=permissions.includes('kpi.review');
  async function load(){setError('');const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/ruang-kawan/');return;}
    const [accessR,memberR,workspaceR]=await Promise.all([supabase.rpc('get_my_access'),supabase.rpc('current_membership_id'),supabase.rpc('list_kpi_workspace')]);const access=Array.isArray(accessR.data)?accessR.data[0]:accessR.data;
    if(!access?.permissions?.includes('kpi.view_self')){setState('denied');return;}if(workspaceR.error){setError(workspaceR.error.message);setState('ready');return;}
    const data=workspaceR.data as {roles:KpiRole[];periods:Period[];members:Member[];assignments:Assignment[]};const currentMember=memberR.data as string;setPermissions(access.permissions??[]);setMembershipId(currentMember);setRoles(data.roles??[]);setPeriods(data.periods??[]);setMembers(data.members??[]);setAssignments(data.assignments??[]);const defaultPeriod=data.periods?.find(period=>period.status==='open')?.id??data.periods?.[0]?.id??'';setPeriodFilter(value=>value||defaultPeriod);setState('ready');
    const currentAssignment=data.assignments?.find(item=>item.membership_id===currentMember&&(!defaultPeriod||item.period_id===defaultPeriod))??data.assignments?.find(item=>item.membership_id===currentMember);if(!selected&&currentAssignment){setSelected(currentAssignment);await refreshDetail(currentAssignment.id);}
    if(access.permissions?.includes('kpi.manage')){const matrix=await supabase.rpc('kpi_role_access_matrix');if(!matrix.error)setAccessMatrix((matrix.data??[]) as AccessRow[]);}if(selected){const fresh=data.assignments?.find(item=>item.id===selected.id);if(fresh)setSelected(fresh);}
  }
  useEffect(()=>{void load();},[]);
  async function refreshDetail(assignmentId:string){const response=await createClient().rpc('kpi_assignment_detail',{target_assignment_id:assignmentId});if(response.error){setError(response.error.message);return;}const detail=response.data as {results:Result[];weeks:Week[];updates:WeeklyUpdate[]};setResults(detail.results??[]);setWeeks(detail.weeks??[]);setUpdates(detail.updates??[]);}
  async function openAssignment(item:Assignment){setSelected(item);await refreshDetail(item.id);}
  const filtered=useMemo(()=>assignments.filter(item=>(!periodFilter||item.period_id===periodFilter)&&(mode==='mine'?item.membership_id===membershipId:mode==='review'?item.status==='submitted'&&(canReview||item.reviewer_membership_id===membershipId):true)),[assignments,periodFilter,mode,membershipId,canReview]);
  const activeRole=roles.find(role=>role.id===templateForm.kpi_role_id);const selectedRole=roles.find(role=>role.id===selected?.kpi_role_id);const existingAssignment=assignments.find(item=>item.period_id===assignmentForm.period_id&&item.membership_id===assignmentForm.membership_id);
  const ownEditable=Boolean(selected&&selected.membership_id===membershipId&&['active','revision_requested'].includes(selected.status));
  const reviewEditable=Boolean(selected&&selected.status==='submitted'&&(canReview||selected.reviewer_membership_id===membershipId));
  const stats={people:filtered.length,onTrack:filtered.filter(a=>(a.final_score??0)>=80).length,attention:filtered.filter(a=>a.final_score!=null&&a.final_score<80).length,review:filtered.filter(a=>a.status==='submitted').length};
  const currentDate=today();const currentWeek=weeks.find(week=>week.week_start<=currentDate&&week.week_end>=currentDate);
  const editHint=!selected?'Pilih assignment terlebih dahulu.':selected.membership_id!==membershipId?'Assignment ini milik anggota lain.':selected.status==='submitted'?'KPI sudah diajukan dan sedang menunggu review.':selected.status==='reviewed'?'KPI sudah disetujui reviewer.':selected.status==='locked'?'Periode KPI sudah dikunci.':selected.status==='cancelled'?'Assignment KPI dibatalkan.':'KPI dapat diperbarui.';
  async function changeMode(next:WorkspaceMode){setMode(next);setSelected(null);setResults([]);setWeeks([]);setUpdates([]);const candidates=assignments.filter(item=>(!periodFilter||item.period_id===periodFilter)&&(next==='mine'?item.membership_id===membershipId:next==='review'?item.status==='submitted'&&(canReview||item.reviewer_membership_id===membershipId):true));if(next!=='setup'&&candidates[0])await openAssignment(candidates[0]);}
  async function changePeriod(value:string){setPeriodFilter(value);setSelected(null);setResults([]);setWeeks([]);setUpdates([]);if(mode==='setup')return;const candidate=assignments.find(item=>(!value||item.period_id===value)&&(mode==='mine'?item.membership_id===membershipId:item.status==='submitted'&&(canReview||item.reviewer_membership_id===membershipId)));if(candidate)await openAssignment(candidate);}

  function show(type:Modal){setError('');if(type==='role')setRoleForm({id:'',name:'',description:'',scoring_model:'staff_equal'});if(type==='category')setCategoryForm({id:'',kpi_role_id:roles.find(r=>r.scoring_model==='category_weighted')?.id??roles[0]?.id??'',name:'',weight:'35',sort_order:'10'});if(type==='template')setTemplateForm({id:'',kpi_role_id:roles[0]?.id??'',category_id:'',code:'',name:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,aggregation_method:'sum',sort_order:'100'});if(type==='period')setPeriodForm({id:'',name:'',start_date:today().slice(0,8)+'01',end_date:monthEnd(),status:'open'});if(type==='assignment'){setAssignmentEditId('');setAssignmentForm({membership_id:members[0]?.id??'',period_id:periods.find(p=>p.status!=='locked')?.id??'',kpi_role_id:roles[0]?.id??'',reviewer_membership_id:''});}if(type==='personal')setPersonalForm({name:'',category_id:'',formula_type:'higher_better',target_value:'',unit:'unit',item_weight:'',evidence_required:true,aggregation_method:'sum'});setModal(type);}
  function editRole(role:KpiRole){setRoleForm({id:role.id,name:role.name,description:role.description??'',scoring_model:role.scoring_model});setModal('role');}
  function editCategory(category:Category){setCategoryForm({id:category.id,kpi_role_id:category.kpi_role_id,name:category.name,weight:String(category.weight),sort_order:String(category.sort_order)});setModal('category');}
  function editTemplate(template:Template){setTemplateForm({id:template.id,kpi_role_id:template.kpi_role_id,category_id:template.category_id??'',code:template.code,name:template.name,formula_type:template.formula_type,target_value:String(template.target_value),unit:template.unit,item_weight:template.item_weight==null?'':String(template.item_weight),evidence_required:template.evidence_required,aggregation_method:template.aggregation_method??'sum',sort_order:String(template.sort_order)});setModal('template');}
  async function getPeriodImpact(periodId:string){const response=await createClient().rpc('kpi_period_impact',{target_period_id:periodId});if(response.error){setError(response.error.message);return null;}const impact=response.data as PeriodImpact;setPeriodImpact(impact);return impact;}
  function editPeriod(period:Period){setPeriodForm({id:period.id,name:period.name,start_date:period.start_date,end_date:period.end_date,status:period.status});setPeriodImpact(null);setModal('period');void getPeriodImpact(period.id);}
  function prepareDeletePeriod(period:Period){setPeriodForm({id:period.id,name:period.name,start_date:period.start_date,end_date:period.end_date,status:period.status});setDeleteConfirmation('');setPeriodImpact(null);setModal('periodDelete');void getPeriodImpact(period.id);}
  function editKpiAssignment(item:Assignment){setAssignmentEditId(item.id);setAssignmentForm({membership_id:item.membership_id,period_id:item.period_id,kpi_role_id:item.kpi_role_id,reviewer_membership_id:item.reviewer_membership_id??''});setModal('assignment');setError('');}
  async function prepareDeleteKpiAssignment(item:Assignment){setAssignmentEditId(item.id);setAssignmentDeleteConfirmation('');setAssignmentImpact(null);setModal('assignmentDelete');const response=await createClient().rpc('kpi_assignment_impact',{target_assignment_id:item.id});if(response.error)setError(response.error.message);else setAssignmentImpact(response.data as AssignmentImpact);}
  function openWeekly(result:Result,week:Week){const existing=updates.find(item=>item.result_id===result.id&&item.week_start===week.week_start&&item.week_end===week.week_end);setWeeklyForm({result_id:result.id,week_start:week.week_start,week_end:week.week_end,actual_value:existing?.actual_value==null?'':String(existing.actual_value),evidence_url:existing?.evidence_url??'',progress:existing?.progress??'',problem:existing?.problem??'',plan:existing?.plan??'',priority:existing?.priority??'',justification:existing?.justification??''});setResultForm(result);setModal('weekly');}
  async function rpc(name:string,args:Record<string,unknown>,success='Perubahan KPI berhasil disimpan.',refreshSelected=true){setSaving(true);setError('');const response=await createClient().rpc(name,args);setSaving(false);if(response.error){setError(response.error.message);return false;}setModal(null);setMessage(success);await load();if(refreshSelected&&selected)await refreshDetail(selected.id);return true;}
  function saveRole(e:FormEvent){e.preventDefault();void rpc('save_kpi_role',{role_id:roleForm.id||null,payload:roleForm});}function saveCategory(e:FormEvent){e.preventDefault();void rpc('save_kpi_category',{category_id:categoryForm.id||null,payload:categoryForm});}function saveTemplate(e:FormEvent){e.preventDefault();void rpc('save_kpi_template',{template_id:templateForm.id||null,payload:templateForm});}
  function savePeriod(e:FormEvent){e.preventDefault();if(periodForm.end_date<periodForm.start_date){setError('Tanggal selesai tidak boleh lebih awal dari tanggal mulai.');return;}void rpc('save_kpi_period',{period_id:periodForm.id||null,payload:periodForm},periodForm.id?'Periode KPI berhasil diperbarui.':'Periode KPI berhasil dibuat.');}
  async function saveAssignment(e:FormEvent){e.preventDefault();const existing=assignments.find(item=>item.period_id===assignmentForm.period_id&&item.membership_id===assignmentForm.membership_id);if(!assignmentEditId&&existing&&existing.kpi_role_id!==assignmentForm.kpi_role_id){setError(`Assignment existing memakai role ${existing.role_name}. Edit assignment tersebut jika role memang perlu diubah.`);return;}const success=await rpc('assign_kpi',{assignment_id:assignmentEditId||null,payload:assignmentForm},assignmentEditId?'Reviewer Assignment KPI berhasil diperbarui.':existing?'Assignment sebelumnya digunakan kembali; hasil KPI lama tetap dipertahankan.':'Assignment KPI berhasil dibuat.');if(success&&existing){setPeriodFilter(existing.period_id);setSelected(existing);await refreshDetail(existing.id);}}
  async function deleteKpiAssignment(e:FormEvent){e.preventDefault();if(!assignmentEditId||!assignmentImpact||assignmentDeleteConfirmation!==assignmentImpact.member_name)return;const deletedId=assignmentEditId;const success=await rpc('delete_kpi_assignment',{target_assignment_id:deletedId,confirmation_name:assignmentDeleteConfirmation},`Assignment KPI ${assignmentImpact.member_name} berhasil dihapus. Snapshot audit tersimpan.`,false);if(success&&selected?.id===deletedId){setSelected(null);setResults([]);setWeeks([]);setUpdates([]);}}
  async function deletePeriod(e:FormEvent){e.preventDefault();if(!periodForm.id||deleteConfirmation!==periodForm.name)return;const deletedId=periodForm.id;const success=await rpc('delete_kpi_period',{target_period_id:deletedId,confirmation_name:deleteConfirmation},`Periode ${periodForm.name} dan data turunannya berhasil dihapus. Snapshot audit tersimpan.`,false);if(success){if(periodFilter===deletedId)setPeriodFilter('');setSelected(null);setResults([]);setWeeks([]);setUpdates([]);}}
  async function saveResult(e:FormEvent){e.preventDefault();if(!resultForm)return;await rpc('save_kpi_result',{result_id:resultForm.id,payload:{actual_value:resultForm.actual_value??'',evidence_url:resultForm.evidence_url??'',note:resultForm.note??'',is_applicable:resultForm.is_applicable,reviewer_score:resultForm.reviewer_score??'',review_note:resultForm.review_note??''}},reviewEditable?'Penilaian reviewer disimpan.':'Realisasi KPI disimpan.');}
  async function saveWeekly(e:FormEvent){e.preventDefault();await rpc('save_kpi_weekly_update',{target_result_id:weeklyForm.result_id,target_week_start:weeklyForm.week_start,target_week_end:weeklyForm.week_end,payload:weeklyForm},'Pembaruan mingguan berhasil disimpan dan nilai bulanan dihitung ulang.');}
  async function savePersonal(e:FormEvent){e.preventDefault();if(!selected)return;await rpc('create_my_kpi_item',{target_assignment_id:selected.id,payload:personalForm},'KPI personal berhasil ditambahkan.');}
  async function transition(status:'submitted'|'reviewed'|'revision_requested'){if(!selected)return;let reason='';if(status==='revision_requested'){reason=window.prompt('Jelaskan revisi yang harus dilakukan:')?.trim()??'';if(!reason)return;}if(status==='reviewed')reason=window.prompt('Catatan review akhir (opsional):')?.trim()??'';await rpc('transition_kpi_assignment',{target_assignment_id:selected.id,new_status:status,reason:reason||null},status==='submitted'?'KPI diajukan kepada reviewer.':status==='reviewed'?'KPI disetujui reviewer.':'KPI dikembalikan untuk revisi.');}
  async function archive(type:'role'|'category'|'template',id:string,label:string){if(!window.confirm(`Nonaktifkan ${label}? Riwayat assignment lama tetap tersimpan.`))return;await rpc('archive_kpi_config',{config_type:type,target_id:id});}

  if(state==='loading')return <main className="rk-kpi-foundation"><section className="rk-access-denied"><p>Menyiapkan KPI Management...</p></section></main>;
  if(state==='denied')return <main className="rk-kpi-foundation"><section className="rk-access-denied"><h1>KPI Management belum tersedia</h1><p>Kamu belum memiliki izin KPI.</p><Link href="/ruang-kawan/dashboard/">Kembali</Link></section></main>;
  return <main className="rk-kpi-foundation"><section className="rk-kpi-shell">
    <nav className="rk-kpi-nav"><Link href="/ruang-kawan/dashboard/"><FiArrowLeft/> Dashboard</Link><button onClick={()=>void load()}><FiRefreshCw/> Muat ulang</button></nav>
    <header className="rk-kpi-heading"><div><small>Performance workspace</small><h1>KPI Management</h1><p>KPI pribadi, review tim, dan konfigurasi admin dipisahkan agar setiap tindakan lebih jelas.</p></div>{canManage?<div><button onClick={()=>void changeMode('setup')}><FiSettings/> Kelola KPI</button></div>:null}</header>
    <nav className="rk-kpi-mode-nav" aria-label="Mode KPI"><button data-active={mode==='mine'} onClick={()=>void changeMode('mine')}><FiTarget/> KPI Saya</button>{canReview||assignments.some(item=>item.reviewer_membership_id===membershipId)?<button data-active={mode==='review'} onClick={()=>void changeMode('review')}><FiAward/> Review Tim <b>{assignments.filter(item=>item.status==='submitted'&&(canReview||item.reviewer_membership_id===membershipId)).length}</b></button>:null}{canManage?<button data-active={mode==='setup'} onClick={()=>void changeMode('setup')}><FiSettings/> Pengaturan KPI</button>:null}</nav>
    {mode==='mine'?<section className="rk-kpi-flow" aria-label="Alur KPI"><div data-active><b>1</b><span><strong>Aktif</strong><small>PIC mengisi aktual dan bukti</small></span></div><i/><div><b>2</b><span><strong>Menunggu Review</strong><small>Data terkunci untuk PIC</small></span></div><i/><div><b>3</b><span><strong>Review / Revisi</strong><small>Reviewer menilai atau mengembalikan</small></span></div><i/><div><b>4</b><span><strong>Approved & Locked</strong><small>Admin mengunci periode</small></span></div></section>:null}
    {mode!=='setup'?<section className="rk-kpi-stats"><article><FiUsers/><span><strong>{stats.people}</strong><small>{mode==='mine'?'KPI saya':'Perlu direview'}</small></span></article><article><FiCheckCircle/><span><strong>{stats.onTrack}</strong><small>On Track</small></span></article><article data-alert={stats.attention>0}><FiTarget/><span><strong>{stats.attention}</strong><small>Perlu perhatian</small></span></article><article data-alert={stats.review>0}><FiAward/><span><strong>{stats.review}</strong><small>Menunggu review</small></span></article></section>:null}
    <section className="rk-kpi-toolbar"><label>Periode<select value={periodFilter} onChange={e=>void changePeriod(e.target.value)}><option value="">Semua periode</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} · {p.start_date}–{p.end_date} · {p.status}</option>)}</select></label>{mode!=='setup'?<div className="rk-kpi-view-switch"><button data-active={view==='card'} onClick={()=>setView('card')}><FiGrid/> Card</button><button data-active={view==='list'} onClick={()=>setView('list')}><FiList/> Daftar</button></div>:null}{mode==='setup'&&canManage?<div><button onClick={()=>show('assignment')}><FiUsers/> Assign KPI</button><button onClick={()=>show('period')}><FiCalendar/> Periode</button><button onClick={()=>show('category')}><FiBarChart2/> Kategori</button><button onClick={()=>show('template')}><FiSettings/> Item KPI</button><button onClick={()=>show('role')}><FiPlus/> Role</button></div>:null}</section>
    {message?<p className="rk-kpi-alert">{message}</p>:null}{error?<p className="rk-kpi-alert" data-error>{error}</p>:null}
    {mode!=='setup'?<section className="rk-kpi-layout"><div className="rk-kpi-list">{filtered.map(item=><button key={item.id} data-active={selected?.id===item.id} onClick={()=>void openAssignment(item)}><span data-score={item.score_status}>{score(item.final_score)}</span><div><small>{item.role_name}</small><strong>{item.member_name}</strong><p>{statusLabels[item.status]} · coverage {score(item.coverage)}</p></div></button>)}{!filtered.length?<p className="rk-kpi-empty">{mode==='mine'?'Belum ada KPI yang ditugaskan kepadamu pada periode ini.':'Tidak ada KPI yang menunggu review.'}</p>:null}</div>
      <div className="rk-kpi-workspace">{selected?<><header><div><small>{selected.role_name}</small><h2>{selected.member_name}</h2><p>Nilai final <b>{score(selected.final_score)}</b> · capaian mentah {score(selected.raw_score)} · coverage {score(selected.coverage)}</p></div><em data-kpi-status={selected.status}>{statusLabels[selected.status]}</em></header>
        {selected.review_note?<p className="rk-kpi-review-note"><FiRotateCcw/> {selected.review_note}</p>:null}
        {selected.scoring_model==='category_weighted'?<section className="rk-kpi-formula"><strong>C-Level</strong><span>Aktivitas Operasional 35%</span><span>Output / Deliverables 35%</span><span>Impact Bisnis 30%</span></section>:<section className="rk-kpi-formula"><strong>Role KPI</strong><span>Rata-rata seluruh KPI aktif</span><span>Skor reguler maksimal 100%</span></section>}
        <div className="rk-kpi-work-actions"><div>{ownEditable&&results.length?<button data-primary onClick={()=>document.querySelector('.rk-kpi-results')?.scrollIntoView({behavior:'smooth',block:'start'})}><FiEdit3/> {currentWeek?'Update KPI minggu ini':'Isi aktual KPI'}</button>:null}{ownEditable&&permissions.includes('kpi.create_self')?<button onClick={()=>show('personal')}><FiPlus/> Tambah KPI saya</button>:null}</div><small data-locked={!ownEditable}>{ownEditable?(currentWeek?'Pilih tombol kuning “Minggu ini” pada KPI yang ingin diperbarui.':'Tanggal hari ini berada di luar rentang periode. Pilih minggu yang tersedia untuk mengisi aktual KPI.'):reviewEditable?'Periksa bukti dan nilai setiap KPI sebelum menyelesaikan review.':editHint}</small></div>
        {view==='card'?<div className="rk-kpi-results">{results.map(item=><article key={item.id}><header><div><small>{item.category_name||item.code} · {formulas[item.formula_type]}</small><strong>{item.name}</strong><p>Target {item.target_value} {item.unit} · {aggregations[item.aggregation_method]}{item.evidence_required?' · evidence wajib':''}</p></div><span><b>{score(item.reviewer_score??item.score)}</b><small>Aktual {item.actual_value??'—'} · raw {score(item.raw_achievement)}</small></span></header><div>{weeks.map(week=>{const update=updates.find(value=>value.result_id===item.id&&value.week_start===week.week_start);const isCurrent=week.week_start===currentWeek?.week_start;return <button key={week.week_start} disabled={!ownEditable} onClick={()=>openWeekly(item,week)} data-filled={update?.actual_value!=null} data-current={isCurrent} title={ownEditable?`Perbarui ${item.name} untuk ${week.label}`:editHint}><small>{isCurrent?'Minggu ini':week.label}{ownEditable?' · update':''}</small><strong>{update?.actual_value??'—'} / {item.target_value}</strong></button>;})}</div>{reviewEditable?<button className="rk-kpi-review-button" onClick={()=>{setResultForm(item);setModal('result');}}><FiEdit3/> Nilai & catatan review</button>:null}</article>)}{!results.length?<p className="rk-kpi-empty">Belum ada item KPI. PIC dapat menambahkan KPI personal saat assignment aktif.</p>:null}</div>:
        <div className="rk-kpi-table-wrap"><table className="rk-kpi-table"><thead><tr><th>KPI</th><th>Target bulanan</th>{weeks.map(week=><th key={week.week_start}>{week.label}</th>)}<th>Kumulatif</th><th>Capaian</th><th>Status</th></tr></thead><tbody>{results.map(item=><tr key={item.id}><th><strong>{item.name}</strong><small>{item.category_name||item.code}</small></th><td>{item.target_value} {item.unit}</td>{weeks.map(week=>{const update=updates.find(value=>value.result_id===item.id&&value.week_start===week.week_start);return <td key={week.week_start}><button disabled={!ownEditable} onClick={()=>openWeekly(item,week)}>{update?.actual_value??'—'}<small>/ {item.target_value}</small></button></td>})}<td>{item.actual_value??'—'} {item.unit}</td><td>{score(item.reviewer_score??item.score)}</td><td><span data-score={item.score!=null&&item.score>=80?'On Track':'At Risk'}>{item.score==null?'Belum dinilai':item.score>=80?'On Track':'Perlu perhatian'}</span></td></tr>)}</tbody></table></div>}
        <footer>{ownEditable?<button onClick={()=>void transition('submitted')}><FiCheckCircle/> Ajukan review</button>:null}{reviewEditable?<><button data-secondary onClick={()=>void transition('revision_requested')}><FiRotateCcw/> Minta revisi</button><button onClick={()=>void transition('reviewed')}><FiAward/> Setujui KPI</button></>:null}</footer>
      </>:<div className="rk-kpi-select-empty"><FiTarget/><h2>{mode==='mine'?'KPI Saya':'Review Tim'}</h2><p>{mode==='mine'?'Assignment milikmu akan otomatis dipilih ketika tersedia.':'Pilih anggota yang menunggu review.'}</p></div>}</div>
    </section>:null}
    {mode==='setup'&&canManage?<><section className="rk-kpi-access-matrix"><header><FiUsers/><div><small>Role access audit</small><h2>Hak KPI seluruh system role</h2></div></header><div>{accessMatrix.map(row=><article key={row.role_key}><strong>{row.role_name}</strong><span>{row.permissions.map(permission=><small key={permission}>{permission.replace('kpi.','')}</small>)}</span></article>)}</div></section>
      <section className="rk-kpi-assignment-admin"><header><div><FiUsers/><span><small>Live readiness</small><h2>Assignment KPI per role</h2></span></div><p>KPI dinyatakan live jika role memiliki template dan setidaknya satu anggota sudah di-assign pada periode terpilih.</p></header><div className="rk-kpi-role-readiness">{roles.map(role=>{const roleAssignments=assignments.filter(item=>item.kpi_role_id===role.id&&(!periodFilter||item.period_id===periodFilter));const live=role.templates.length>0&&roleAssignments.length>0;return <article key={role.id} data-ready={live}><span><strong>{role.name}</strong><small>{role.templates.length} template · {roleAssignments.length} assignment</small></span><b>{live?'Live':role.templates.length?'Belum di-assign':'Template kosong'}</b></article>;})}</div><div className="rk-kpi-assignment-list">{assignments.filter(item=>!periodFilter||item.period_id===periodFilter).map(item=><article key={item.id}><div><small>{item.period_id===periodFilter?periods.find(period=>period.id===item.period_id)?.name:item.role_name}</small><strong>{item.member_name}</strong><p>{item.role_name} · {statusLabels[item.status]}{item.reviewer_membership_id?' · reviewer terpasang':' · reviewer belum dipilih'}</p></div><span><button onClick={()=>editKpiAssignment(item)} aria-label={`Edit assignment ${item.member_name}`}><FiEdit3/> Edit</button><button data-danger onClick={()=>void prepareDeleteKpiAssignment(item)} aria-label={`Hapus assignment ${item.member_name}`}><FiTrash2/> Hapus</button></span></article>)}{!assignments.some(item=>!periodFilter||item.period_id===periodFilter)?<p>Belum ada assignment pada periode ini.</p>:null}</div></section>
      <section className="rk-kpi-config"><header><div><FiSettings/><span><small>Admin configuration</small><h2>Role dan template KPI</h2></span></div><p>Perubahan template hanya berlaku untuk assignment baru.</p></header><div>{roles.map(role=><article key={role.id}><header><div><strong>{role.name}</strong><small>{role.scoring_model==='category_weighted'?'Kategori berbobot':'Rata-rata KPI aktif'} · {role.templates.length} item</small></div><span><button onClick={()=>editRole(role)} aria-label={`Edit ${role.name}`}><FiEdit3/></button><button onClick={()=>void archive('role',role.id,role.name)} aria-label={`Nonaktifkan ${role.name}`}><FiTrash2/></button></span></header>{role.categories.length?<div className="rk-kpi-config-categories">{role.categories.map(category=><div key={category.id}><button onClick={()=>editCategory(category)}>{category.name} <b>{category.weight}%</b></button><button onClick={()=>void archive('category',category.id,category.name)}><FiTrash2/></button></div>)}</div>:null}<div className="rk-kpi-config-items">{role.templates.map(template=><div key={template.id}><button onClick={()=>editTemplate(template)}><span>{template.code}</span><strong>{template.name}</strong><small>{template.target_value} {template.unit} · {aggregations[template.aggregation_method]}</small></button><button onClick={()=>void archive('template',template.id,template.name)}><FiTrash2/></button></div>)}{!role.templates.length?<p>Belum ada template. Assignment tetap dapat dibuat lalu PIC menambahkan KPI personal.</p>:null}</div></article>)}</div><footer><strong>Periode</strong>{periods.map(period=><div className="rk-kpi-period-action" key={period.id}><button onClick={()=>editPeriod(period)} aria-label={`Edit periode ${period.name}`} title={`Edit ${period.name}`}><span>{period.name}</span><small>{period.start_date} — {period.end_date} · {period.status}</small><FiEdit3/></button><button data-danger onClick={()=>prepareDeletePeriod(period)} aria-label={`Hapus periode ${period.name}`} title={`Hapus ${period.name}`}><FiTrash2/> Hapus</button></div>)}</footer></section></>:null}
  </section>
  {modal?<div className="rk-kpi-modal"><form onSubmit={modal==='role'?saveRole:modal==='category'?saveCategory:modal==='template'?saveTemplate:modal==='period'?savePeriod:modal==='periodDelete'?deletePeriod:modal==='assignment'?saveAssignment:modal==='assignmentDelete'?deleteKpiAssignment:modal==='weekly'?saveWeekly:modal==='personal'?savePersonal:saveResult}><header><div><small>Ruang kerja KPI</small><h2>{modal==='role'?'KPI Role':modal==='category'?'Kategori berbobot':modal==='template'?'Template KPI':modal==='period'?(periodForm.id?'Edit periode KPI':'Periode KPI'):modal==='periodDelete'?`Hapus ${periodForm.name}`:modal==='assignment'?(assignmentEditId?'Edit Assignment KPI':'Assign KPI'):modal==='assignmentDelete'?`Hapus Assignment KPI`:modal==='weekly'?`${resultForm?.name} · update mingguan`:modal==='personal'?'Tambah KPI saya':`Review · ${resultForm?.name}`}</h2></div><button type="button" onClick={()=>setModal(null)}><FiX/></button></header><div className="rk-kpi-form">
    {modal==='role'?<><label>Nama role<input value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})} required/></label><label>Model penilaian<select value={roleForm.scoring_model} onChange={e=>setRoleForm({...roleForm,scoring_model:e.target.value})}><option value="staff_equal">Staf · rata-rata KPI aktif</option><option value="category_weighted">C-Level · kategori berbobot</option></select></label><label className="wide">Deskripsi<textarea value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})}/></label></>:null}
    {modal==='category'?<><label>Role<select value={categoryForm.kpi_role_id} onChange={e=>setCategoryForm({...categoryForm,kpi_role_id:e.target.value})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Nama<input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} required/></label><label>Bobot (%)<input type="number" min="0.01" max="100" value={categoryForm.weight} onChange={e=>setCategoryForm({...categoryForm,weight:e.target.value})} required/></label></>:null}
    {modal==='template'?<><label>Role<select value={templateForm.kpi_role_id} onChange={e=>setTemplateForm({...templateForm,kpi_role_id:e.target.value,category_id:''})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{activeRole?.scoring_model==='category_weighted'?<label>Kategori<select value={templateForm.category_id} onChange={e=>setTemplateForm({...templateForm,category_id:e.target.value})} required><option value="">Pilih kategori</option>{activeRole.categories.map(c=><option key={c.id} value={c.id}>{c.name} · {c.weight}%</option>)}</select></label>:null}<label>Kode<input value={templateForm.code} onChange={e=>setTemplateForm({...templateForm,code:e.target.value})} required/></label><label className="wide">Nama KPI<input value={templateForm.name} onChange={e=>setTemplateForm({...templateForm,name:e.target.value})} required/></label><label>Rumus<select value={templateForm.formula_type} onChange={e=>setTemplateForm({...templateForm,formula_type:e.target.value})}>{Object.entries(formulas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Agregasi<select value={templateForm.aggregation_method} onChange={e=>setTemplateForm({...templateForm,aggregation_method:e.target.value})}>{Object.entries(aggregations).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Target<input type="number" step="0.0001" value={templateForm.target_value} onChange={e=>setTemplateForm({...templateForm,target_value:e.target.value})} required/></label><label>Satuan<input value={templateForm.unit} onChange={e=>setTemplateForm({...templateForm,unit:e.target.value})} required/></label><label><input type="checkbox" checked={templateForm.evidence_required} onChange={e=>setTemplateForm({...templateForm,evidence_required:e.target.checked})}/> Evidence wajib</label></>:null}
    {modal==='period'?<><label>Nama periode<input value={periodForm.name} onChange={e=>setPeriodForm({...periodForm,name:e.target.value})} required/></label><label>Mulai<input type="date" value={periodForm.start_date} onChange={e=>setPeriodForm({...periodForm,start_date:e.target.value})} required/></label><label>Selesai<input type="date" min={periodForm.start_date} value={periodForm.end_date} onChange={e=>setPeriodForm({...periodForm,end_date:e.target.value})} required/></label><label>Status<select value={periodForm.status} onChange={e=>setPeriodForm({...periodForm,status:e.target.value})}><option value="draft">Draft</option><option value="open">Open</option><option value="review">Review</option><option value="locked">Locked</option></select></label>{periodForm.id&&periodImpact&&periodImpact.assignment_count>0?<div className="rk-kpi-impact wide" role="note"><FiAward/><div><strong>Periode sudah dipakai</strong><p>Perubahan tanggal memengaruhi {periodImpact.assignment_count} assignment dan {periodImpact.result_count} hasil KPI. Assignment tidak dibuat ulang otomatis.</p></div></div>:null}</>:null}
    {modal==='periodDelete'?<div className="rk-kpi-delete-period wide"><p>Penghapusan hanya dapat dilakukan oleh pengelola KPI. Seluruh data turunan disimpan sebagai snapshot audit sebelum dihapus.</p>{periodImpact?<div className="rk-kpi-impact-grid"><span><b>{periodImpact.assignment_count}</b>Assignment</span><span><b>{periodImpact.result_count}</b>Hasil KPI</span><span><b>{periodImpact.weekly_update_count}</b>Update mingguan</span><span><b>{periodImpact.evidence_count}</b>Evidence</span></div>:<p>Memuat dampak periode...</p>}<label>Ketik <strong>{periodForm.name}</strong> untuk konfirmasi<input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} autoComplete="off" required/></label></div>:null}
    {modal==='assignment'?<><label>Anggota<select value={assignmentForm.membership_id} disabled={Boolean(assignmentEditId)} onChange={e=>setAssignmentForm({...assignmentForm,membership_id:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Periode<select value={assignmentForm.period_id} disabled={Boolean(assignmentEditId)} onChange={e=>setAssignmentForm({...assignmentForm,period_id:e.target.value})}>{periods.filter(p=>p.status!=='locked'||p.id===assignmentForm.period_id).map(p=><option key={p.id} value={p.id}>{p.name} · {p.start_date}–{p.end_date}</option>)}</select></label><label>Role KPI<select value={assignmentForm.kpi_role_id} disabled={Boolean(assignmentEditId)} onChange={e=>setAssignmentForm({...assignmentForm,kpi_role_id:e.target.value})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Reviewer<select value={assignmentForm.reviewer_membership_id} onChange={e=>setAssignmentForm({...assignmentForm,reviewer_membership_id:e.target.value})}><option value="">Belum ditentukan</option>{members.filter(m=>m.id!==assignmentForm.membership_id).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{assignmentEditId?<div className="rk-kpi-impact wide"><FiEdit3/><div><strong>Edit aman</strong><p>Anggota, periode, dan role dikunci agar hasil KPI lama tidak berpindah konteks. Reviewer dapat diperbarui tanpa menghapus hasil.</p></div></div>:existingAssignment?<div className="rk-kpi-impact wide" data-error={existingAssignment.kpi_role_id!==assignmentForm.kpi_role_id}><FiRotateCcw/><div><strong>Assignment sebelumnya ditemukan</strong><p>{existingAssignment.member_name} sudah memiliki assignment {existingAssignment.role_name} pada periode ini. {existingAssignment.kpi_role_id===assignmentForm.kpi_role_id?'Simpan akan menggunakan assignment lama dan mempertahankan seluruh hasil KPI.':'Pilih role yang sama atau edit assignment existing; role tidak akan ditimpa diam-diam.'}</p></div></div>:null}</>:null}
    {modal==='assignmentDelete'?<div className="rk-kpi-delete-period wide"><p>Assignment dan data turunannya akan dihapus dari workspace. Snapshot lengkap tetap disimpan pada audit admin.</p>{assignmentImpact?<><div className="rk-kpi-impact-grid"><span><b>{assignmentImpact.result_count}</b>Hasil KPI</span><span><b>{assignmentImpact.weekly_update_count}</b>Update mingguan</span><span><b>{assignmentImpact.evidence_count}</b>Evidence</span><span><b>{assignmentImpact.period_name}</b>{assignmentImpact.role_name}</span></div><label>Ketik <strong>{assignmentImpact.member_name}</strong> untuk konfirmasi<input value={assignmentDeleteConfirmation} onChange={e=>setAssignmentDeleteConfirmation(e.target.value)} autoComplete="off" required/></label></>:<p>Memuat dampak assignment...</p>}</div>:null}
    {modal==='weekly'?<><label>Rentang minggu<input value={`${weeklyForm.week_start} — ${weeklyForm.week_end}`} disabled/></label><label>Aktual<input type="number" step="0.0001" value={weeklyForm.actual_value} onChange={e=>setWeeklyForm({...weeklyForm,actual_value:e.target.value})}/></label><label className="wide">Evidence URL<input type="url" value={weeklyForm.evidence_url} onChange={e=>setWeeklyForm({...weeklyForm,evidence_url:e.target.value})} required={resultForm?.evidence_required}/></label><label className="wide">Progress<textarea value={weeklyForm.progress} onChange={e=>setWeeklyForm({...weeklyForm,progress:e.target.value})}/></label><label className="wide">Problem<textarea value={weeklyForm.problem} onChange={e=>setWeeklyForm({...weeklyForm,problem:e.target.value})}/></label><label className="wide">Plan<textarea value={weeklyForm.plan} onChange={e=>setWeeklyForm({...weeklyForm,plan:e.target.value})}/></label><label className="wide">Priority<textarea value={weeklyForm.priority} onChange={e=>setWeeklyForm({...weeklyForm,priority:e.target.value})}/></label><label className="wide">Justifikasi<textarea value={weeklyForm.justification} onChange={e=>setWeeklyForm({...weeklyForm,justification:e.target.value})}/></label></>:null}
    {modal==='personal'?<><label className="wide">Nama KPI<input value={personalForm.name} onChange={e=>setPersonalForm({...personalForm,name:e.target.value})} required/></label>{selectedRole?.scoring_model==='category_weighted'?<label>Kategori<select value={personalForm.category_id} onChange={e=>setPersonalForm({...personalForm,category_id:e.target.value})} required><option value="">Pilih kategori</option>{selectedRole.categories.map(c=><option key={c.id} value={c.id}>{c.name} · {c.weight}%</option>)}</select></label>:null}<label>Rumus<select value={personalForm.formula_type} onChange={e=>setPersonalForm({...personalForm,formula_type:e.target.value})}>{Object.entries(formulas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Agregasi<select value={personalForm.aggregation_method} onChange={e=>setPersonalForm({...personalForm,aggregation_method:e.target.value})}>{Object.entries(aggregations).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Target bulanan<input type="number" min="0" step="0.0001" value={personalForm.target_value} onChange={e=>setPersonalForm({...personalForm,target_value:e.target.value})} required/></label><label>Satuan<input value={personalForm.unit} onChange={e=>setPersonalForm({...personalForm,unit:e.target.value})} required/></label><label><input type="checkbox" checked={personalForm.evidence_required} onChange={e=>setPersonalForm({...personalForm,evidence_required:e.target.checked})}/> Evidence wajib</label></>:null}
    {modal==='result'&&resultForm?<><label>Aktual terkumpul<input value={resultForm.actual_value??''} disabled/></label><label>Evidence<input value={resultForm.evidence_url??''} disabled/></label><label>Nilai reviewer<input type="number" min="0" max="100" step="0.01" value={resultForm.reviewer_score??''} onChange={e=>setResultForm({...resultForm,reviewer_score:e.target.value===''?null:Number(e.target.value)})}/></label><label className="wide">Catatan review<textarea value={resultForm.review_note??''} onChange={e=>setResultForm({...resultForm,review_note:e.target.value})}/></label></>:null}
    </div>{error?<p className="rk-kpi-modal-error">{error}</p>:null}<footer><button type="button" onClick={()=>setModal(null)}>Batal</button><button data-primary data-danger={modal==='periodDelete'||modal==='assignmentDelete'} disabled={saving||(modal==='periodDelete'&&deleteConfirmation!==periodForm.name)||(modal==='assignmentDelete'&&(!assignmentImpact||assignmentDeleteConfirmation!==assignmentImpact.member_name))}>{saving?(modal==='periodDelete'||modal==='assignmentDelete'?'Menghapus...':'Menyimpan...'):modal==='periodDelete'?'Hapus periode':modal==='assignmentDelete'?'Hapus assignment':assignmentEditId&&modal==='assignment'?'Simpan perubahan':'Simpan'}</button></footer></form></div>:null}
  </main>;
}
