'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { sha256, OfficeDocument } from '@/lib/office/types';
export default function VerifyCredential() {
  const [data, setData] = useState<{ document: OfficeDocument; signers: { name: string; approved_at: string | null }[] } | null>(null);
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [checking, setChecking] = useState(false);
  useEffect(() => { void (async () => { const token = new URLSearchParams(window.location.search).get('credential'); if (!token || !/^[a-f0-9-]{36}$/i.test(token)) { setError('Kredensial tidak valid.'); return; } const result = await createClient().rpc('verify_office_credential', { token }); if (result.error) { setError('Masuk menggunakan akun peserta dokumen, lalu pindai QR kembali. Kredensial juga mungkin tidak ditemukan.'); return; } setData(result.data); })(); }, []);
  async function verify(file?: File) { if (!file || !data) return; setChecking(true); setMessage(''); try { if (file.size > 25 * 1024 * 1024) throw new Error('PDF maksimal 25 MB.'); const hash = await sha256(await file.arrayBuffer()); setMessage(hash === data.document.output_hash ? 'Cocok: file identik dengan PDF hasil yang tercatat.' : 'Tidak cocok: file berbeda dari PDF hasil yang tercatat.'); } catch (e) { setError(e instanceof Error ? e.message : 'File gagal diperiksa.'); } finally { setChecking(false); } }
  return <main className="rk-office"><section className="rk-office-panel"><small>Campus Innovate · Digital Office</small><h1>Verifikasi kredensial QR</h1>{error ? <p className="rk-office-error" role="alert">{error}</p> : !data ? <p>Memeriksa kredensial…</p> : <><h2>{data.document.title}</h2><p>Status: {data.document.status === 'completed' ? 'Selesai' : data.document.status === 'pending' ? 'Belum selesai' : 'Dibatalkan'}</p><code>{data.document.credential}</code>{data.signers.map((s, i) => <p key={i}>{s.name} · {s.approved_at ? new Date(s.approved_at).toLocaleString('id-ID') : 'Belum menyetujui'}</p>)}{data.document.output_hash ? <><p>SHA-256 PDF hasil:</p><code className="rk-office-hash">{data.document.output_hash}</code><label>Periksa file PDF yang diterima<input disabled={checking} type="file" accept="application/pdf" onChange={event => void verify(event.target.files?.[0])} /></label>{message ? <p role="status">{message}</p> : null}</> : null}<p>Kredensial ini merupakan catatan persetujuan internal Campus Innovate. Pemeriksaan file membandingkan hash dengan PDF hasil yang didaftarkan.</p></>}<Link href="/ruang-kawan/digital-office/">Kembali ke Digital Office</Link></section></main>;
}
