'use client';
import { FormEvent, useEffect, useState } from 'react';
import { rpc, write, operationKey, uploadEvidence, evidenceUrl, Request, writesEnabled } from '@/lib/finance-pilot/api';
import styles from './finance-pilot.module.css';
type Scoped = { position: string; projects: { id: string; project_code: string; name: string; service_line_key: string; delivery_confirmed_at: string | null }[]; receivables: { id: string; invoice_number: string; client: string; balance: number; due_date: string }[]; requests: Request[] };
export default function ScopedWorkspace() {
 const [data,setData]=useState<Scoped|null>(null); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [saving,setSaving]=useState(false);
 const [project,setProject]=useState(''); const [amount,setAmount]=useState(''); const [description,setDescription]=useState(''); const [evidence,setEvidence]=useState(''); const [kind,setKind]=useState('claim');
 async function load(){try{setData(await rpc<Scoped>('finance_pilot_scoped_workspace'));}catch(e){setError(e instanceof Error?e.message:'Gagal memuat.');}}
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const payload={kind,project,amount,description,evidence};await write('finance_pilot_submit_scoped',{p_key:await operationKey('scoped',payload),p_kind:kind,p_project:project||null,p_amount:amount,p_description:description,p_evidence:evidence});setNotice('Pengajuan tersimpan. Belum menjadi transaksi atau jurnal.');await load();}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan.');}finally{setSaving(false);}}
 async function attach(file?:File){if(!file)return;setSaving(true);try{setEvidence(await uploadEvidence(file));}catch(e){setError(e instanceof Error?e.message:'Upload gagal.');}finally{setSaving(false);}}
 async function confirm(id:string){const note=window.prompt('Bukti handover/delivery teknis:');if(!note)return;setSaving(true);try{await write('finance_pilot_confirm_delivery',{p_project_id:id,p_evidence:note});await load();setNotice('Konfirmasi delivery tersimpan. Closure finansial tetap oleh COO.');}catch(e){setError(e instanceof Error?e.message:'Gagal.');}finally{setSaving(false);}}
 return <main className={styles.page}><header className={styles.header}><div><h1>Finance Pilot</h1><p>{data?.position} · akses hanya pengajuan sendiri dan project yang ditugaskan.</p></div><button onClick={()=>void load()}>Refresh</button></header>{error?<p className={styles.alert} role="alert">{error}</p>:null}{notice?<p className={styles.notice}>{notice}</p>:null}
 <section className={styles.panel}><h2>Pengajuan bukti / expense claim</h2><p>Pengajuan diterima COO untuk klasifikasi dan workflow finance. Tidak memberi hak posting jurnal atau akses laporan perusahaan.</p><form className={styles.form} onSubmit={e=>void submit(e)}><label>Jenis<select value={kind} onChange={e=>setKind(e.target.value)}><option value="claim">Expense claim / evidence</option>{data?.position==='cto'?<option value="estimate">Delivery cost estimate</option>:null}</select></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)} required={kind==='estimate'}><option value="">Operasional / tanpa project</option>{data?.projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select></label><label>Nominal<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required /></label><label>Keperluan<textarea value={description} onChange={e=>setDescription(e.target.value)} required /></label><label>Bukti privat<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>void attach(e.target.files?.[0])} disabled={saving||!writesEnabled} /><small>{evidence}</small></label><button disabled={saving||!writesEnabled}>Kirim pengajuan</button></form></section>
 <section className={styles.panel}><h2>Project ditugaskan</h2>{data?.projects.map(p=><article key={p.id}><b>{p.project_code} · {p.name}</b>{data.position==='cto'&&p.service_line_key==='digital_system'?<button disabled={saving||!writesEnabled} onClick={()=>void confirm(p.id)}>Konfirmasi delivery teknis</button>:null}</article>)}</section>
 {data?.position==='business_development_staff'?<section className={styles.panel}><h2>Collection follow-up ditugaskan</h2>{data.receivables.map(r=><p key={r.id}>{r.invoice_number} · {r.client} · Rp{Number(r.balance).toLocaleString('id-ID')} · due {r.due_date}</p>)}</section>:null}
 <section className={styles.panel}><h2>Pengajuan saya</h2>{data?.requests.map(r=><article key={r.id}><b>{r.kind} · {r.state}</b><p>{String(r.payload.description)} · {r.review_note}</p><button onClick={()=>void evidenceUrl(String(r.payload.evidence_path)).then(url=>window.open(url,'_blank','noopener,noreferrer')).catch(e=>setError(e.message))}>Buka bukti</button></article>)}</section></main>;
}
