const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const migration=name=>fs.readFileSync(`supabase/migrations/${name}`,'utf8');
const extract=(sql,name)=>sql.match(new RegExp(`create or replace function public\\.${name}\\([\\s\\S]*?\\$\\$;`))[0];
const table=(sql,name)=>sql.match(new RegExp(`create table public\\.${name} \\([\\s\\S]*?\\n\\);`))[0];
const actor='00000000-0000-4000-8000-000000000001';
test('partial Pipeline save preserves non-form fields, metrics, nested research and rejects stale edits',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create schema extensions;
  create table auth.users(id uuid primary key); insert into auth.users values('${actor}');
  create function extensions.gen_random_uuid() returns uuid language sql as $$select gen_random_uuid()$$;
  create function auth.uid() returns uuid language sql as $$select '${actor}'::uuid$$;
  create function current_membership_id() returns uuid language sql as $$select auth.uid()$$;
  create function current_user_has_permission(text) returns boolean language sql as $$select true$$;
  create function can_access_work_source(uuid) returns boolean language sql as $$select true$$;
  create function can_access_activity(uuid) returns boolean language sql as $$select true$$;
  create table memberships(id uuid primary key,status text); insert into memberships values('${actor}','active');
  create table work_sources(id uuid primary key,module_type text,module_config jsonb);
  create table activity_history(activity_id uuid,actor_membership_id uuid,event_type text,after_data jsonb);
  create table notifications(recipient_membership_id uuid,actor_membership_id uuid,notification_type text,title text,message text,entity_type text,entity_id text,action_url text);`);
  await db.exec(table(migration('20260824130000_ruang_kawan_activity_calendar.sql'),'activities'));
  await db.exec('alter table activities add column assigned_by_membership_id uuid');
  const original=migration('20260825130000_ruang_kawan_pipeline_bd.sql');
  await db.exec(table(original,'pipeline_leads'));
  const os=migration('20261002000605_pipeline_operating_system.sql');
  await db.exec(os.match(/alter table public\.pipeline_leads[\s\S]*?qualification_reason text;/)[0]);
  await db.exec(extract(original,'save_pipeline_lead'));
  await db.exec(extract(os,'pipeline_prepare_lead'));
  await db.exec(`create trigger prep before insert or update on pipeline_leads for each row execute function pipeline_prepare_lead();
  create function sync_pipeline_tickets() returns trigger language plpgsql as $$begin return new; end$$;
  create function refresh_pipeline_contact_metrics() returns trigger language plpgsql as $$begin return new; end$$;`);
  await db.exec(migration('20261002005935_pipeline_preserve_edits.sql'));
  const source=(await db.query(`insert into work_sources values(gen_random_uuid(),'pipeline','{"stages":["Target","Won"],"priorities":["Medium"],"activity_types":["Follow Up"]}') returning id`)).rows[0].id;
  const originalPayload={source_id:source,account_name:'Regression fixture',stage:'Target',next_action:'Call',due_date:'2026-10-10',trip_program:'Trip',seats:4,price_per_person:900,payment_status:'Lunas',probability:0.5,follow_up_count:8,last_contact_date:'2026-09-20',business_unit:'Legacy',account_type:'School',linked_kpi:'Outreach',document_url:'https://example.com/doc',extra_data:{research:{notes:'Keep me'},proposal_value:1000,won_value:800,email_contact:'a@example.com',qualification:{evidence:'Keep evidence',need:true}}};
  const id=(await db.query('select save_pipeline_lead(null,$1) id',[originalPayload])).rows[0].id;
  const get=async()=> (await db.query('select to_jsonb(pl) data from pipeline_leads pl where id=$1',[id])).rows[0].data;
  const before=await get();
  await db.query('select save_pipeline_lead($1,$2)',[id,{notes:'Edited note',extra_data:{qualification:{budget:true}},follow_up_count:0,last_contact_date:''}]);
  const after=await get();
  for(const key of ['trip_program','seats','price_per_person','payment_status','probability','follow_up_count','last_contact_date','business_unit','account_type','document_url'])assert.deepEqual(after[key],before[key],key);
  assert.equal(after.notes,'Edited note');assert.deepEqual(after.extra_data.research,{notes:'Keep me'});
  assert.equal(after.extra_data.qualification.evidence,'Keep evidence');assert.equal(after.extra_data.qualification.need,true);assert.equal(after.extra_data.qualification.budget,true);
  assert.equal((await db.query('select linked_kpi from activities where id=$1',[after.activity_id])).rows[0].linked_kpi,'Outreach');
  await assert.rejects(db.query('select save_pipeline_lead($1,$2)',[id,{notes:'stale',expected_updated_at:'2000-01-01T00:00:00Z'}]),/telah berubah/);
  await db.query('select save_pipeline_lead($1,$2)',[id,{extra_data:{proposal_value:'',won_value:'',email_contact:''}}]);
  const cleared=await get();assert.equal(cleared.proposal_value,null);assert.equal(cleared.won_value,null);assert.equal(cleared.email_contact,null);
  await db.query('select save_pipeline_lead($1,$2)',[id,{stage:'Won',extra_data:{proposal_value:1000,won_value:''}}]);
  assert.equal((await get()).won_value,null,'Won must not infer project revenue from GM/proposal');
 }finally{await db.close()}
});
