'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { FiArrowDownLeft, FiArrowLeft, FiArrowUpRight, FiBox, FiFileText, FiPlus, FiRefreshCw, FiRotateCcw, FiTrendingUp, FiX } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Tx={id:string;transaction_number:string;transaction_date:string;event_type:string;flow:'in'|'out'|'non_cash';category:string;description:string;counterparty:string|null;amount:number;status:string;reference_number:string|null;reversal_of_id:string|null};
type Doc={id:string;document_type:'quotation'|'invoice'|'receipt';document_number:string;document_date:string;due_date:string|null;client:string;project_name:string|null;status:string;total:number;paid:number;balance:number;linked_invoice_id:string|null;google_doc_url:string|null;pdf_url:string|null};
type Budget={id:string;period_month:string;category:string;budget_type:string;planned_amount:number;status:string};
type Asset={id:string;asset_code:string;asset_name:string;category:string|null;acquisition_value:number;condition:string};
type Account={id:string;code:string;name:string;account_type:string;opening_balance:number};
type TxForm={date:string;eventType:'income'|'expense'|'adjustment';flow:'in'|'out'|'non_cash';accountId:string;category:string;description:string;counterparty:string;amount:string;reference:string;evidence:string};
type DocForm={type:'quotation'|'invoice'|'receipt';date:string;dueDate:string;client:string;address:string;project:string;itemName:string;quantity:string;unitPrice:string;discount:string;tax:string;notes:string;invoiceId:string;receiptAmount:string};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const emptyTx=():TxForm=>({date:today(),eventType:'expense',flow:'out',accountId:'',category:'',description:'',counterparty:'',amount:'',reference:'',evidence:''});
const emptyDoc=():DocForm=>({type:'quotation',date:today(),dueDate:'',client:'',address:'',project:'',itemName:'',quantity:'1',unitPrice:'',discount:'0',tax:'0',notes:'',invoiceId:'',receiptAmount:''});
const money=(value:number|string)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(value)||0);

export default function FinancePage(){
 const [state,setState]=useState<'loading'|'ready'|'denied'>('loading');const [permissions,setPermissions]=useState<string[]>([]);const [tab,setTab]=useState<'overview'|'transactions'|'documents'|'planning'>('overview');const [transactions,setTransactions]=useState<Tx[]>([]);const [documents,setDocuments]=useState<Doc[]>([]);const [budgets,setBudgets]=useState<Budget[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [txForm,setTxForm]=useState<TxForm>(emptyTx());const [docForm,setDocForm]=useState<DocForm>(emptyDoc());const [modal,setModal]=useState<'tx'|'doc'|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(){setError('');const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/ruang-kawan/');return;}const accessR=await supabase.rpc('get_my_access');const access=Array.isArray(accessR.data)?accessR.data[0]:accessR.data;if(!access?.permissions?.includes('finance.view')){setState('denied');return;}setPermissions(access.permissions??[]);const [txR,docR,budgetR,assetR,accountR]=await Promise.all([supabase.from('finance_transactions').select('*').order('transaction_date',{ascending:false}).limit(200),supabase.from('finance_documents').select('*').is('deleted_at',null).order('document_date',{ascending:false}).limit(200),supabase.from('finance_budgets').select('*').order('period_month',{ascending:false}),supabase.from('finance_assets').select('*').eq('is_active',true).order('asset_name'),supabase.from('finance_accounts').select('*').eq('is_active',true).order('code')]);setTransactions((txR.data??[]) as Tx[]);setDocuments((docR.data??[]) as Doc[]);setBudgets((budgetR.data??[]) as Budget[]);setAssets((assetR.data??[]) as Asset[]);setAccounts((accountR.data??[]) as Account[]);setState('ready');}
 useEffect(()=>{void load();},[]);
 const totals=useMemo(()=>({cashIn:transactions.filter(x=>x.status==='posted'&&x.flow==='in').reduce((s,x)=>s+Number(x.amount),0),cashOut:transactions.filter(x=>x.status==='posted'&&x.flow==='out').reduce((s,x)=>s+Number(x.amount),0),receivable:documents.filter(x=>x.document_type==='invoice').reduce((s,x)=>s+Number(x.balance),0),budget:budgets.filter(x=>x.status==='active').reduce((s,x)=>s+Number(x.planned_amount),0)}),[transactions,documents,budgets]);
 const canManage=permissions.includes('finance.manage');
 async function saveTx(e:FormEvent){e.preventDefault();setSaving(true);setError('');const r=await createClient().rpc('finance_create_transaction',{tx_date:txForm.date,tx_event_type:txForm.eventType,tx_flow:txForm.flow,tx_account_id:txForm.accountId||null,tx_category:txForm.category,tx_description:txForm.description,tx_counterparty:txForm.counterparty,tx_amount:Number(txForm.amount),tx_reference:txForm.reference,tx_evidence_url:txForm.evidence});setSaving(false);if(r.error){setError(r.error.message);return;}setModal(null);setTxForm(emptyTx());setMessage('Transaksi berhasil diposting.');await load();}
 async function reverse(tx:Tx){const reason=window.prompt(`Alasan reversal ${tx.transaction_number}:`);if(!reason)return;const r=await createClient().rpc('finance_reverse_transaction',{target_transaction_id:tx.id,reason});if(r.error)setError(r.error.message);else{setMessage('Reversal tercatat tanpa menghapus transaksi asal.');await load();}}
 async function saveDoc(e:FormEvent){e.preventDefault();setSaving(true);setError('');const items=docForm.type==='receipt'?[]:[{description:docForm.itemName,quantity:Number(docForm.quantity),unit_price:Number(docForm.unitPrice)}];const linked=documents.find(x=>x.id===docForm.invoiceId);const r=await createClient().rpc('finance_create_document',{doc_type:docForm.type,doc_date:docForm.date,doc_due_date:docForm.dueDate||null,doc_client:docForm.type==='receipt'?(linked?.client??''):docForm.client,doc_client_address:docForm.address,doc_project:docForm.project,doc_discount:Number(docForm.discount),doc_tax:Number(docForm.tax),doc_notes:docForm.notes,doc_items:items,doc_linked_invoice_id:docForm.invoiceId||null,receipt_amount:Number(docForm.receiptAmount)||0});setSaving(false);if(r.error){setError(r.error.message);return;}setModal(null);setDocForm(emptyDoc());setMessage('Dokumen Finance tersimpan dan jurnal terkait diperbarui.');await load();}
 if(state==='loading')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><p>Menyiapkan Finance...</p></section></main>;
 if(state==='denied')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><h1>Akses Finance belum tersedia</h1><p>Admin dapat memberikan izin Finance melalui pengaturan anggota.</p><Link href="/ruang-kawan/dashboard/">Kembali</Link></section></main>;
 return <main className="rk-work-foundation"><section className="rk-work-shell"><nav className="rk-work-nav"><Link href="/ruang-kawan/dashboard/"><FiArrowLeft/> Dashboard</Link><button onClick={()=>void load()}><FiRefreshCw/> Muat ulang</button></nav><header className="rk-work-heading"><div><small>Finance Control</small><h1>Finance</h1><p>Ringkasan kas, transaksi, piutang, dokumen, budget, dan aset dalam satu kontrol yang dapat diaudit.</p></div>{canManage?<div><button onClick={()=>setModal('tx')}><FiPlus/> Transaksi</button><button onClick={()=>setModal('doc')}><FiFileText/> Dokumen</button></div>:null}</header>
 <section className="rk-finance-cards"><article><FiArrowDownLeft/><span><small>Kas masuk</small><strong>{money(totals.cashIn)}</strong></span></article><article><FiArrowUpRight/><span><small>Kas keluar</small><strong>{money(totals.cashOut)}</strong></span></article><article><FiTrendingUp/><span><small>Piutang outstanding</small><strong>{money(totals.receivable)}</strong></span></article><article><FiBox/><span><small>Budget aktif</small><strong>{money(totals.budget)}</strong></span></article></section>
 <div className="rk-work-tabs">{([['overview','Ringkasan'],['transactions','Jurnal'],['documents','Dokumen'],['planning','Budget & Aset']] as const).map(([key,label])=><button key={key} data-active={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>{message?<p className="rk-work-alert">{message}</p>:null}{error?<p className="rk-work-alert" data-error>{error}</p>:null}
 {tab==='overview'?<section className="rk-finance-overview"><article><header><small>Posisi kas</small><h2>{money(totals.cashIn-totals.cashOut)}</h2></header><div><span>Total masuk<strong>{money(totals.cashIn)}</strong></span><span>Total keluar<strong>{money(totals.cashOut)}</strong></span><span>Piutang<strong>{money(totals.receivable)}</strong></span></div></article><article><header><small>Dokumen terbaru</small><h2>{documents.length} dokumen</h2></header>{documents.slice(0,5).map(doc=><div key={doc.id}><span>{doc.document_number}<small>{doc.client}</small></span><b>{money(doc.total)}</b><em>{doc.status}</em></div>)}</article></section>:null}
 {tab==='transactions'?<section className="rk-finance-table"><header><div><small>Jurnal transaksi</small><h2>Riwayat yang dapat diaudit</h2></div>{canManage?<button onClick={()=>setModal('tx')}><FiPlus/> Tambah</button>:null}</header><div className="rk-table-scroll"><table><thead><tr><th>Nomor</th><th>Tanggal</th><th>Keterangan</th><th>Flow</th><th>Nominal</th><th>Status</th><th/></tr></thead><tbody>{transactions.map(tx=><tr key={tx.id}><td><strong>{tx.transaction_number}</strong><small>{tx.category}</small></td><td>{new Date(`${tx.transaction_date}T12:00:00`).toLocaleDateString('id-ID')}</td><td>{tx.description}<small>{tx.counterparty}</small></td><td><em data-flow={tx.flow}>{tx.flow}</em></td><td>{money(tx.amount)}</td><td>{tx.status}</td><td>{canManage&&tx.status==='posted'&&!tx.reversal_of_id?<button title="Reversal" onClick={()=>void reverse(tx)}><FiRotateCcw/></button>:null}</td></tr>)}</tbody></table></div></section>:null}
 {tab==='documents'?<section className="rk-finance-table"><header><div><small>QUO · INV · RCP</small><h2>Dokumen bisnis</h2></div>{canManage?<button onClick={()=>setModal('doc')}><FiPlus/> Buat dokumen</button>:null}</header><div className="rk-table-scroll"><table><thead><tr><th>Nomor</th><th>Client/Project</th><th>Tanggal</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{documents.map(doc=><tr key={doc.id}><td><strong>{doc.document_number}</strong><small>{doc.document_type.toUpperCase()}</small></td><td>{doc.client}<small>{doc.project_name}</small></td><td>{doc.document_date}{doc.due_date?<small>Due {doc.due_date}</small>:null}</td><td>{money(doc.total)}</td><td>{money(doc.paid)}</td><td>{money(doc.balance)}</td><td><em data-doc-status={doc.status}>{doc.status}</em></td></tr>)}</tbody></table></div></section>:null}
 {tab==='planning'?<section className="rk-finance-planning"><article><header><small>Budget</small><h2>{budgets.length} pos</h2></header>{budgets.map(x=><div key={x.id}><span>{x.category}<small>{x.period_month.slice(0,7)} · {x.budget_type}</small></span><strong>{money(x.planned_amount)}</strong></div>)}</article><article><header><small>Aset</small><h2>{assets.length} aset aktif</h2></header>{assets.map(x=><div key={x.id}><span>{x.asset_name}<small>{x.asset_code} · {x.category}</small></span><strong>{money(x.acquisition_value)}</strong><em>{x.condition}</em></div>)}</article></section>:null}</section>
 {modal==='tx'?<div className="rk-work-modal"><form onSubmit={saveTx}><header><div><small>Jurnal</small><h2>Tambah transaksi</h2></div><button type="button" onClick={()=>setModal(null)}><FiX/></button></header><div className="rk-work-form rk-form-two"><label>Tanggal<input type="date" value={txForm.date} onChange={e=>setTxForm({...txForm,date:e.target.value})} required/></label><label>Jenis<select value={txForm.eventType} onChange={e=>{const type=e.target.value as TxForm['eventType'];setTxForm({...txForm,eventType:type,flow:type==='income'?'in':type==='expense'?'out':'non_cash'});}}><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option><option value="adjustment">Adjustment</option></select></label><label>Flow<select value={txForm.flow} onChange={e=>setTxForm({...txForm,flow:e.target.value as TxForm['flow']})}><option value="in">Masuk</option><option value="out">Keluar</option><option value="non_cash">Non-cash</option></select></label><label>Akun<select value={txForm.accountId} onChange={e=>setTxForm({...txForm,accountId:e.target.value})}><option value="">Belum ditetapkan</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Kategori<input value={txForm.category} onChange={e=>setTxForm({...txForm,category:e.target.value})} required/></label><label>Nominal<input type="number" min="1" value={txForm.amount} onChange={e=>setTxForm({...txForm,amount:e.target.value})} required/></label><label className="wide">Keterangan<input value={txForm.description} onChange={e=>setTxForm({...txForm,description:e.target.value})} required/></label><label>Pihak terkait<input value={txForm.counterparty} onChange={e=>setTxForm({...txForm,counterparty:e.target.value})}/></label><label>Referensi<input value={txForm.reference} onChange={e=>setTxForm({...txForm,reference:e.target.value})}/></label><label className="wide">URL bukti<input type="url" value={txForm.evidence} onChange={e=>setTxForm({...txForm,evidence:e.target.value})}/></label></div><footer><span/><div><button type="button" onClick={()=>setModal(null)}>Batal</button><button data-primary disabled={saving}>{saving?'Memposting...':'Posting transaksi'}</button></div></footer></form></div>:null}
 {modal==='doc'?<div className="rk-work-modal"><form onSubmit={saveDoc}><header><div><small>Documents</small><h2>Buat dokumen Finance</h2></div><button type="button" onClick={()=>setModal(null)}><FiX/></button></header><div className="rk-work-form rk-form-two"><label>Tipe<select value={docForm.type} onChange={e=>setDocForm({...emptyDoc(),type:e.target.value as DocForm['type']})}><option value="quotation">Quotation</option><option value="invoice">Invoice</option><option value="receipt">Payment Receipt</option></select></label><label>Tanggal<input type="date" value={docForm.date} onChange={e=>setDocForm({...docForm,date:e.target.value})} required/></label>{docForm.type==='receipt'?<><label className="wide">Invoice<select value={docForm.invoiceId} onChange={e=>setDocForm({...docForm,invoiceId:e.target.value})} required><option value="">Pilih invoice outstanding</option>{documents.filter(x=>x.document_type==='invoice'&&Number(x.balance)>0).map(x=><option key={x.id} value={x.id}>{x.document_number} · {x.client} · {money(x.balance)}</option>)}</select></label><label className="wide">Nominal diterima<input type="number" min="1" value={docForm.receiptAmount} onChange={e=>setDocForm({...docForm,receiptAmount:e.target.value})} required/></label></>:<><label>Client<input value={docForm.client} onChange={e=>setDocForm({...docForm,client:e.target.value})} required/></label><label>Project<input value={docForm.project} onChange={e=>setDocForm({...docForm,project:e.target.value})}/></label>{docForm.type==='invoice'?<label>Jatuh tempo<input type="date" value={docForm.dueDate} onChange={e=>setDocForm({...docForm,dueDate:e.target.value})}/></label>:null}<label className="wide">Alamat client<textarea value={docForm.address} onChange={e=>setDocForm({...docForm,address:e.target.value})}/></label><label className="wide">Item<input value={docForm.itemName} onChange={e=>setDocForm({...docForm,itemName:e.target.value})} required/></label><label>Jumlah<input type="number" min="0.01" step="0.01" value={docForm.quantity} onChange={e=>setDocForm({...docForm,quantity:e.target.value})}/></label><label>Harga satuan<input type="number" min="1" value={docForm.unitPrice} onChange={e=>setDocForm({...docForm,unitPrice:e.target.value})} required/></label><label>Diskon<input type="number" min="0" value={docForm.discount} onChange={e=>setDocForm({...docForm,discount:e.target.value})}/></label><label>Pajak<input type="number" min="0" value={docForm.tax} onChange={e=>setDocForm({...docForm,tax:e.target.value})}/></label></>}<label className="wide">Catatan<textarea value={docForm.notes} onChange={e=>setDocForm({...docForm,notes:e.target.value})}/></label></div><footer><span/><div><button type="button" onClick={()=>setModal(null)}>Batal</button><button data-primary disabled={saving}>{saving?'Menyimpan...':'Simpan dokumen'}</button></div></footer></form></div>:null}</main>;
}
