'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { FiArrowLeft, FiCheckCircle, FiClock, FiEdit3, FiMessageSquare, FiPlus, FiRefreshCw, FiSend, FiX } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Member={id:string;name:string;email:string;position:string|null};
type Source={id:string;name:string;color:string};
type Assignment={id:string;owner_membership_id:string;assigned_by_membership_id:string|null;reviewer_membership_id:string|null;source_id:string;title:string;activity_date:string;priority:'low'|'medium'|'high'|'urgent';status:'not_started'|'in_progress'|'done'|'blocked';progress:number;detail:string|null;output:string|null;next_action:string|null;evidence_url:string|null;review_status:'not_submitted'|'waiting_review'|'approved'|'revision_requested';review_note:string|null;owner_name:string;assigned_by_name:string|null;reviewer_name:string|null;source_name:string;source_color:string};
type Comment={id:string;body:string;created_at:string;author_membership_id:string};
type Form={id:string|null;ownerId:string;reviewerId:string;sourceId:string;title:string;date:string;priority:Assignment['priority'];detail:string;output:string;nextAction:string;evidenceUrl:string};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const emptyForm=():Form=>({id:null,ownerId:'',reviewerId:'',sourceId:'',title:'',date:today(),priority:'medium',detail:'',output:'',nextAction:'',evidenceUrl:''});
const reviewLabels={not_submitted:'Belum diajukan',waiting_review:'Menunggu review',approved:'Disetujui',revision_requested:'Perlu revisi'};
const statusLabels={not_started:'Belum mulai',in_progress:'Berjalan',done:'Selesai',blocked:'Terhambat'};

export default function AssignmentsPage(){
  const [state,setState]=useState<'loading'|'ready'|'denied'>('loading'); const [membershipId,setMembershipId]=useState('');
  const [permissions,setPermissions]=useState<string[]>([]);const [members,setMembers]=useState<Member[]>([]);const [sources,setSources]=useState<Source[]>([]);const [items,setItems]=useState<Assignment[]>([]);
  const [filter,setFilter]=useState('active');const [form,setForm]=useState<Form>(emptyForm());const [formOpen,setFormOpen]=useState(false);const [selected,setSelected]=useState<Assignment|null>(null);const [comments,setComments]=useState<Comment[]>([]);const [comment,setComment]=useState('');const [reviewNote,setReviewNote]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(){setError('');const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/ruang-kawan/');return;}
    const [accessR,memberR,membersR,sourcesR,itemsR]=await Promise.all([supabase.rpc('get_my_access'),supabase.rpc('current_membership_id'),supabase.rpc('list_assignable_members'),supabase.rpc('list_my_work_sources'),supabase.rpc('list_accessible_assignments')]);
    const access=Array.isArray(accessR.data)?accessR.data[0]:accessR.data;if(!access?.permissions?.includes('activity.view_self')){setState('denied');return;}
    setPermissions(access.permissions??[]);setMembershipId(memberR.data as string);setMembers((membersR.data??[]) as Member[]);setSources((sourcesR.data??[]) as Source[]);setItems((itemsR.data??[]) as Assignment[]);setState('ready');}
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>items.filter(item=>filter==='all'||(filter==='review'?item.review_status==='waiting_review':filter==='done'?item.status==='done':item.status!=='done')),[items,filter]);
  function openCreate(){const own=members.find(x=>x.id===membershipId);setForm({...emptyForm(),ownerId:own?.id??membershipId,sourceId:sources[0]?.id??''});setFormOpen(true);setError('');}
  function openEdit(item:Assignment){setForm({id:item.id,ownerId:item.owner_membership_id,reviewerId:item.reviewer_membership_id??'',sourceId:item.source_id,title:item.title,date:item.activity_date,priority:item.priority,detail:item.detail??'',output:item.output??'',nextAction:item.next_action??'',evidenceUrl:item.evidence_url??''});setFormOpen(true);setError('');}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError('');const result=await createClient().rpc('save_assignment',{assignment_id:form.id,target_membership_id:form.ownerId||membershipId,target_reviewer_id:form.reviewerId||null,target_source_id:form.sourceId,assignment_title:form.title,assignment_date:form.date,assignment_priority:form.priority,assignment_detail:form.detail,assignment_output:form.output,assignment_next_action:form.nextAction,assignment_evidence_url:form.evidenceUrl});setSaving(false);if(result.error){setError(result.error.message);return;}setFormOpen(false);setMessage(form.id?'Assignment diperbarui.':'Assignment berhasil diberikan.');await load();}
  async function openDetail(item:Assignment){setSelected(item);setReviewNote(item.review_note??'');const result=await createClient().from('activity_comments').select('*').eq('activity_id',item.id).order('created_at');setComments((result.data??[]) as Comment[]);}
  async function addComment(event:FormEvent){event.preventDefault();if(!selected||!comment.trim())return;const result=await createClient().from('activity_comments').insert({activity_id:selected.id,author_membership_id:membershipId,body:comment.trim()});if(result.error)setError(result.error.message);else{setComment('');await openDetail(selected);}}
  async function submitReview(){if(!selected)return;const result=await createClient().rpc('submit_activity_review',{target_activity_id:selected.id});if(result.error)setError(result.error.message);else{setSelected(null);setMessage('Pekerjaan diajukan untuk review.');await load();}}
  async function review(decision:'approved'|'revision_requested'){if(!selected)return;const result=await createClient().rpc('review_activity',{target_activity_id:selected.id,decision,note:reviewNote});if(result.error)setError(result.error.message);else{setSelected(null);setMessage(decision==='approved'?'Pekerjaan disetujui.':'Pekerjaan dikembalikan untuk revisi.');await load();}}
  if(state==='loading')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><p>Menyiapkan Assignment...</p></section></main>;
  if(state==='denied')return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><h1>Assignment belum tersedia</h1><Link href="/ruang-kawan/activity/">Kembali ke My Activity</Link></section></main>;
  const canAssign=permissions.includes('activity.assign_team');
  return <main className="rk-work-foundation"><section className="rk-work-shell"><nav className="rk-work-nav"><Link href="/ruang-kawan/activity/"><FiArrowLeft/> My Activity</Link><button onClick={()=>void load()}><FiRefreshCw/> Muat ulang</button></nav>
    <header className="rk-work-heading"><div><small>Kerja tim</small><h1>Assignment</h1><p>Tugaskan pekerjaan, diskusikan hasil, dan selesaikan review dalam satu alur.</p></div>{canAssign?<button onClick={openCreate}><FiPlus/> Berikan assignment</button>:null}</header>
    <section className="rk-assignment-stats"><article><FiClock/><span><strong>{items.filter(x=>x.status!=='done').length}</strong><small>Aktif</small></span></article><article><FiSend/><span><strong>{items.filter(x=>x.review_status==='waiting_review').length}</strong><small>Menunggu review</small></span></article><article><FiCheckCircle/><span><strong>{items.filter(x=>x.review_status==='approved').length}</strong><small>Disetujui</small></span></article></section>
    <div className="rk-work-tabs">{[['active','Aktif'],['review','Perlu Review'],['done','Selesai'],['all','Semua']].map(([key,label])=><button key={key} data-active={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
    {message?<p className="rk-work-alert">{message}</p>:null}{error?<p className="rk-work-alert" data-error>{error}</p>:null}
    <section className="rk-assignment-list">{visible.map(item=><article key={item.id}><i style={{background:item.source_color}}/><button className="rk-assignment-main" onClick={()=>void openDetail(item)}><span><small>{item.source_name} · {new Date(`${item.activity_date}T12:00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</small><b data-priority={item.priority}>{item.priority}</b></span><h2>{item.title}</h2><p>{item.detail||'Tidak ada detail tambahan.'}</p><footer><em data-status={item.status}>{statusLabels[item.status]}</em><strong>{item.owner_name}</strong><span data-review={item.review_status}>{reviewLabels[item.review_status]}</span></footer></button>{canAssign||item.assigned_by_membership_id===membershipId?<button className="rk-icon-button" onClick={()=>openEdit(item)}><FiEdit3/></button>:<span/>}</article>)}{!visible.length?<div className="rk-work-empty"><FiCheckCircle/><strong>Tidak ada assignment pada filter ini</strong></div>:null}</section>
  </section>
  {formOpen?<div className="rk-work-modal"><form onSubmit={save}><header><div><small>Assignment</small><h2>{form.id?'Ubah pekerjaan':'Berikan pekerjaan'}</h2></div><button type="button" onClick={()=>setFormOpen(false)}><FiX/></button></header><div className="rk-work-form rk-form-two"><label>PIC<select value={form.ownerId} onChange={e=>setForm({...form,ownerId:e.target.value})} required>{(members.length?members:[{id:membershipId,name:'Saya',email:'',position:null}]).map(x=><option key={x.id} value={x.id}>{x.name}{x.position?` · ${x.position}`:''}</option>)}</select></label><label>Reviewer<select value={form.reviewerId} onChange={e=>setForm({...form,reviewerId:e.target.value})}><option value="">Tanpa reviewer</option>{members.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Sumber kerja<select value={form.sourceId} onChange={e=>setForm({...form,sourceId:e.target.value})} required>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Deadline<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label className="wide">Judul<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Prioritas<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Assignment['priority']})}><option value="low">Rendah</option><option value="medium">Sedang</option><option value="high">Tinggi</option><option value="urgent">Mendesak</option></select></label><label className="wide">Detail<textarea value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})}/></label><label className="wide">Output yang diharapkan<textarea value={form.output} onChange={e=>setForm({...form,output:e.target.value})}/></label><label className="wide">Next action<textarea value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label><label className="wide">URL bukti<input type="url" value={form.evidenceUrl} onChange={e=>setForm({...form,evidenceUrl:e.target.value})}/></label></div><footer><span/><div><button type="button" onClick={()=>setFormOpen(false)}>Batal</button><button data-primary disabled={saving}>{saving?'Menyimpan...':'Simpan'}</button></div></footer></form></div>:null}
  {selected?<div className="rk-work-modal"><section className="rk-assignment-detail"><header><div><small>{selected.source_name}</small><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)}><FiX/></button></header><div className="rk-assignment-meta"><span>PIC<strong>{selected.owner_name}</strong></span><span>Pemberi tugas<strong>{selected.assigned_by_name||'Dibuat sendiri'}</strong></span><span>Reviewer<strong>{selected.reviewer_name||'Belum ditetapkan'}</strong></span><span>Review<strong>{reviewLabels[selected.review_status]}</strong></span></div>{selected.detail?<p>{selected.detail}</p>:null}{selected.output?<div className="rk-detail-box"><small>Output</small><p>{selected.output}</p></div>:null}{selected.review_note?<div className="rk-detail-box" data-review><small>Catatan review</small><p>{selected.review_note}</p></div>:null}<section className="rk-comments"><h3><FiMessageSquare/> Diskusi</h3>{comments.map(x=><article key={x.id}><small>{x.author_membership_id===membershipId?'Saya':'Anggota'} · {new Date(x.created_at).toLocaleString('id-ID')}</small><p>{x.body}</p></article>)}<form onSubmit={addComment}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Tulis komentar..."/><button><FiSend/></button></form></section><footer>{selected.owner_membership_id===membershipId&&selected.reviewer_membership_id&&selected.review_status!=='waiting_review'&&selected.review_status!=='approved'?<button onClick={()=>void submitReview()}><FiSend/> Ajukan review</button>:<span/>}{selected.review_status==='waiting_review'&&(selected.reviewer_membership_id===membershipId||permissions.includes('activity.review_team'))?<div><textarea value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Catatan review..."/><span><button data-danger onClick={()=>void review('revision_requested')}>Perlu revisi</button><button data-primary onClick={()=>void review('approved')}>Setujui</button></span></div>:null}</footer></section></div>:null}</main>;
}
