'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useMemo, useRef, useState } from 'react';
import { FiActivity,FiBarChart2,FiBell,FiBookOpen,FiBriefcase,FiChevronDown,FiDollarSign,FiFileText,FiGrid,FiLogOut,FiMessageCircle,FiMoreHorizontal,FiSettings,FiTrendingUp,FiUser } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Access={membership_status:string;permissions:string[];full_name?:string|null;position_name?:string|null};
const items=[
 {label:'Dashboard',href:'/ruang-kawan/dashboard/',icon:FiGrid,any:[]},
 {label:'My Activity',href:'/ruang-kawan/activity/',icon:FiActivity,any:['activity.view_self']},
 {label:'Marketing',href:'/ruang-kawan/marketing/',icon:FiTrendingUp,any:['marketing.view','content_plan.view','pipeline.view']},
 {label:'Project',href:'/ruang-kawan/projects/',icon:FiBriefcase,any:['projects.view']},
 {label:'KPI',href:'/ruang-kawan/kpi/',icon:FiBarChart2,any:['kpi.view_self']},
 {label:'Documents',href:'/ruang-kawan/documents/',icon:FiBookOpen,any:['documents.view']},
 {label:'Reports',href:'/ruang-kawan/reports/',icon:FiFileText,any:['reports.view_self']},
 {label:'Finance',href:'/ruang-kawan/finance/',icon:FiDollarSign,any:['finance.view']},
];

export default function WorkspaceMiniNav(){
 const pathname=usePathname();const[access,setAccess]=useState<Access|null>(null);const[email,setEmail]=useState('');const[hidden,setHidden]=useState(false);const[profileOpen,setProfileOpen]=useState(false);const[moreOpen,setMoreOpen]=useState(false);const[chatUnread,setChatUnread]=useState(0);const[notificationUnread,setNotificationUnread]=useState(0);const lastScroll=useRef(0);const navRef=useRef<HTMLElement>(null);
 useEffect(()=>{let active=true;async function load(){const supabase=createClient();const{data:{session}}=await supabase.auth.getSession();if(!session)return;const[{data},chat]=await Promise.all([supabase.rpc('get_my_access'),supabase.rpc('chat_workspace')]);const value=(Array.isArray(data)?data[0]:data)as Access|null;if(active&&value?.membership_status==='active'){setAccess(value);setEmail(session.user.email??'');if(!chat.error)setChatUnread(Number((chat.data as {unread_total?:number}|null)?.unread_total??0))}}void load();return()=>{active=false}},[]);
 useEffect(()=>{const update=(event:Event)=>setChatUnread(Number((event as CustomEvent<{count?:number}>).detail?.count??0));window.addEventListener('kawan-chat-unread',update);return()=>window.removeEventListener('kawan-chat-unread',update)},[]);
 useEffect(()=>{const update=(event:Event)=>setNotificationUnread(Number((event as CustomEvent<{count?:number}>).detail?.count??0));window.addEventListener('kawan-notification-unread',update);return()=>window.removeEventListener('kawan-notification-unread',update)},[]);
 useEffect(()=>{if(!access)return;const supabase=createClient();const refresh=async()=>{const result=await supabase.rpc('chat_workspace');if(!result.error)setChatUnread(Number((result.data as {unread_total?:number}|null)?.unread_total??0))};const channel=supabase.channel('rk-nav-chat-unread').on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},()=>void refresh()).subscribe();return()=>{void supabase.removeChannel(channel)}},[access]);
 useEffect(()=>{function onScroll(){const next=window.scrollY;if(window.innerWidth>760)setHidden(next>lastScroll.current&&next>110);lastScroll.current=next}function onMove(event:MouseEvent){if(event.clientY<18)setHidden(false)}function onKey(event:KeyboardEvent){if(event.key==='Escape'){setProfileOpen(false);setMoreOpen(false)}}function onClick(event:MouseEvent){if(navRef.current&&!navRef.current.contains(event.target as Node)){setProfileOpen(false);setMoreOpen(false)}}window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('mousemove',onMove);window.addEventListener('keydown',onKey);document.addEventListener('mousedown',onClick);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('mousemove',onMove);window.removeEventListener('keydown',onKey);document.removeEventListener('mousedown',onClick)}},[]);
 const visible=useMemo(()=>items.filter(item=>item.any.length===0||item.any.some(permission=>access?.permissions?.includes(permission))),[access]);
 if(!access||pathname==='/ruang-kawan'||pathname.startsWith('/ruang-kawan/callback'))return null;
 const activeFor=(href:string)=>href==='/ruang-kawan/dashboard/'?pathname.startsWith('/ruang-kawan/dashboard'):href==='/ruang-kawan/marketing/'?['/ruang-kawan/marketing','/ruang-kawan/content-plan','/ruang-kawan/pipeline'].some(route=>pathname.startsWith(route)):pathname.startsWith(href.slice(0,-1));
 async function signOut(){await createClient().auth.signOut();window.location.replace('/ruang-kawan/')}
 const primary=visible.filter(item=>['Dashboard','My Activity','Marketing','Project','KPI'].includes(item.label));const secondary=visible.filter(item=>['Documents','Reports','Finance'].includes(item.label));const mobile=primary.filter(item=>['Dashboard','My Activity','Marketing'].includes(item.label));
 return <><nav ref={navRef} className="rk-mini-nav" data-hidden={hidden} aria-label="Navigasi utama Ruang Kawan"><div className="rk-mini-nav-inner">
  <div className="rk-nav-modules">{primary.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} data-active={activeFor(item.href)}><Icon/><span>{item.label}</span></Link>})}<div className="rk-more-wrap"><button className="rk-nav-more" data-active={secondary.some(item=>activeFor(item.href))||pathname.startsWith('/ruang-kawan/admin')} aria-expanded={moreOpen} onClick={()=>{setMoreOpen(value=>!value);setProfileOpen(false)}}><FiMoreHorizontal/><span>Lainnya</span></button>{moreOpen?<div className="rk-more-dropdown">{secondary.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} data-active={activeFor(item.href)} onClick={()=>setMoreOpen(false)}><Icon/><span><strong>{item.label}</strong><small>{item.label==='Documents'?'Pusat dokumen kerja':item.label==='Reports'?'Laporan dan analisis':'Kontrol keuangan'}</small></span></Link>})}{access.permissions.includes('access.manage')?<Link href="/ruang-kawan/admin/" data-active={pathname.startsWith('/ruang-kawan/admin')} onClick={()=>setMoreOpen(false)}><FiSettings/><span><strong>Admin</strong><small>Anggota dan hak akses</small></span></Link>:null}</div>:null}</div></div>
  <div className="rk-nav-account">
   <Link className="rk-nav-notification rk-nav-chat-link" href="/ruang-kawan/chat/" data-active={pathname.startsWith('/ruang-kawan/chat')} aria-label={`Kawan Chat${chatUnread?`, ${chatUnread} belum dibaca`:''}`}><FiMessageCircle/>{chatUnread?<b>{chatUnread>9?'9+':chatUnread}</b>:null}</Link>
   {access.permissions.includes('notifications.view_self')?<Link className="rk-nav-notification" href="/ruang-kawan/notifications/" data-active={pathname.startsWith('/ruang-kawan/notifications')} aria-label={`Notifikasi${notificationUnread?`, ${notificationUnread} belum dibaca`:''}`}><FiBell/>{notificationUnread?<b>{notificationUnread>9?'9+':notificationUnread}</b>:null}</Link>:null}
   <div><button className="rk-nav-profile" aria-expanded={profileOpen} onClick={()=>{setProfileOpen(value=>!value);setMoreOpen(false)}}><span><FiUser/></span><b>{access.full_name?.split(' ')[0]||'Profil'}</b><FiChevronDown/></button>{profileOpen?<div className="rk-profile-dropdown"><header><strong>{access.full_name||email}</strong><small>{access.position_name||email}</small></header><Link href="/ruang-kawan/profile/" onClick={()=>setProfileOpen(false)}><FiUser/> Profil & akun</Link><button onClick={()=>void signOut()}><FiLogOut/> Keluar</button></div>:null}</div>
  </div>
 </div></nav><nav className="rk-mobile-nav" aria-label="Navigasi mobile Ruang Kawan">{mobile.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} data-active={activeFor(item.href)}><Icon/><span>{item.label==='My Activity'?'Activity':item.label}</span></Link>})}<Link href="/ruang-kawan/chat/" data-active={pathname.startsWith('/ruang-kawan/chat')}><FiMessageCircle/><span>Chat</span>{chatUnread?<b>{chatUnread>9?'9+':chatUnread}</b>:null}</Link>{access.permissions.includes('notifications.view_self')?<Link href="/ruang-kawan/notifications/" data-active={pathname.startsWith('/ruang-kawan/notifications')}><FiBell/><span>Notifikasi</span>{notificationUnread?<b>{notificationUnread>9?'9+':notificationUnread}</b>:null}</Link>:null}<Link href="/ruang-kawan/profile/" data-active={pathname.startsWith('/ruang-kawan/profile')}><FiUser/><span>Profil</span></Link></nav></>
}
