'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { FiArrowRight, FiCheck, FiClock, FiExternalLink, FiFilter, FiMessageCircle, FiRefreshCw, FiSearch, FiUsers } from 'react-icons/fi';
import { createClient } from '@/lib/supabase/client';

type Checklist={id:string;phase:string;label:string;required:boolean;done:boolean;evidence:string|null};
type Ticket={id:string;ticket_code:string;pipeline_lead_id:string;phase:'commercial'|'proposal_deal'|'handover'|'delivery'|'report_close';ticket_status:string;service_main:string;phase_owner_membership_id:string;phase_deadline:string;next_action:string;next_action_due:string;blocker:string|null;conversation_id:string|null;project_id:string|null;project_conversation_id:string|null;account_name:string;lead_code:string;stage:string;lead_source:string|null;deal_value:number|null;owner_name:string;can_contribute:boolean;can_accept_handover:boolean;checklist:Checklist[];members:Array<{membership_id:string;name:string;member_role:string}>;conversation_name:string|null;project_code:string|null};
type Workspace={tickets:Ticket[];members:Array<{id:string;name:string;position:string|null}>;can_manage:boolean;can_transition:boolean};
const phases:Record<Ticket['phase'],string>={commercial:'Commercial',proposal_deal:'Proposal & Deal',handover:'Handover',delivery:'Delivery',report_close:'Report & Close'};
const statusLabels:Record<string,string>={open:'Open',in_progress:'Berjalan',waiting_client:'Menunggu client',blocked:'Terhambat',handover:'Handover',closed_won:'Won',closed_lost:'Lost'};
const nextPhase:Partial<Record<Ticket['phase'],Ticket['phase']>>={commercial:'proposal_deal',proposal_deal:'handover',handover:'delivery',delivery:'report_close'};
const formatDate=(value:string)=>new Date(`${value}T12:00:00+07:00`).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Jakarta'});

export default function TicketingPage(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [phaseFilter,setPhaseFilter]=useState('all');const [selected,setSelected]=useState<Ticket|null>(null);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');const [owner,setOwner]=useState('');const [deadline,setDeadline]=useState('');const [actionDue,setActionDue]=useState('');const [action,setAction]=useState('');const [blocker,setBlocker]=useState('');const [memberId,setMemberId]=useState('');const [memberRole,setMemberRole]=useState<'assignee'|'watcher'|'approver'>('assignee');const [projectLead,setProjectLead]=useState('');
 async function load(){setError('');const db=createClient();const {data:{session}}=await db.auth.getSession();if(!session){window.location.replace('/ruang-kawan/');return;}const {data,error:loadError}=await db.rpc('ticketing_workspace');if(loadError){setError(loadError.message);setLoading(false);return;}setWorkspace(data as Workspace);setLoading(false);}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>{const items=workspace?.tickets??[];const text=query.trim().toLowerCase();return items.filter(x=>(phaseFilter==='all'||x.phase===phaseFilter)&&(!text||`${x.ticket_code} ${x.account_name} ${x.lead_code} ${x.service_main} ${x.owner_name}`.toLowerCase().includes(text)))},[workspace,query,phaseFilter]);
 function open(ticket:Ticket){setSelected(ticket);setOwner(ticket.phase_owner_membership_id);setProjectLead(ticket.phase_owner_membership_id);setDeadline(ticket.phase_deadline);setActionDue(ticket.next_action_due);setAction(ticket.next_action);setBlocker(ticket.blocker??'');setNotice('');}
 async function save(){if(!selected)return;let changeReason:string|null=null;if(deadline!==selected.phase_deadline||actionDue!==selected.next_action_due){changeReason=window.prompt('Alasan perubahan deadline fase atau next action (minimal 5 karakter):')?.trim()??'';if(changeReason.length<5)return;}setSaving(true);setError('');const result=await createClient().rpc('update_commercial_ticket',{target_ticket_id:selected.id,payload:{phase_owner_membership_id:owner,phase_deadline:deadline,next_action:action,next_action_due:actionDue,change_reason:changeReason,blocker,ticket_status:blocker?'blocked':selected.ticket_status==='blocked'?'in_progress':selected.ticket_status}});setSaving(false);if(result.error){setError(result.error.message);return;}setSelected(null);setNotice('Ticket berhasil diperbarui.');await load();}
 async function toggle(item:Checklist,done:boolean){const result=await createClient().rpc('set_commercial_ticket_checklist',{target_checklist_id:item.id,is_done:done,evidence_text:item.evidence??null});if(result.error){setError(result.error.message);return;}await load();const fresh=(await createClient().rpc('ticketing_workspace')).data as Workspace;setWorkspace(fresh);const t=fresh.tickets.find(x=>x.id===selected?.id);if(t){setSelected(t);setOwner(t.phase_owner_membership_id);setDeadline(t.phase_deadline);setAction(t.next_action);setBlocker(t.blocker??'');}}
 async function advance(ticket:Ticket){const phase=nextPhase[ticket.phase];if(!phase)return;let reason='';const incomplete=ticket.checklist.some(x=>x.phase===ticket.phase&&x.required&&!x.done);if(incomplete){reason=window.prompt('Checklist fase belum lengkap. Isi alasan override (approval wajib tetap harus dipenuhi):')?.trim()??'';if(reason.length<5)return;}const result=await createClient().rpc('transition_commercial_ticket',{target_ticket_id:ticket.id,target_phase:phase,transition_reason:reason||null});if(result.error){setError(result.error.message);return;}setNotice(`Fase dipindahkan ke ${phases[phase]}.`);setSelected(null);await load();}
 async function addMember(){if(!selected||!memberId)return;setSaving(true);const result=await createClient().rpc('add_commercial_ticket_members',{target_ticket_id:selected.id,member_ids:[memberId],target_role:memberRole});setSaving(false);if(result.error){setError(result.error.message);return;}setMemberId('');await load();const fresh=(await createClient().rpc('ticketing_workspace')).data as Workspace;setWorkspace(fresh);const t=fresh.tickets.find(x=>x.id===selected.id);if(t)setSelected(t);}
 async function acceptHandover(){if(!selected)return;setSaving(true);const result=await createClient().rpc('accept_commercial_handover',{target_ticket_id:selected.id,target_project_lead_id:projectLead});setSaving(false);if(result.error){setError(result.error.message);return;}setSelected(null);setNotice('Handover diterima; Project dan Project Space sudah diaktifkan.');await load();}
 if(loading)return <main className="rk-dashboard-foundation"><section className="rk-access-denied"><p>Menyiapkan ticket...</p></section></main>;
 return <main className="rk-work-foundation"><section className="rk-work-shell"><nav className="rk-work-nav"><Link href="/ruang-kawan/pipeline/">Pipeline</Link><button onClick={()=>void load()}><FiRefreshCw/> Muat ulang</button></nav>
  <header className="rk-work-heading"><div><small>Commercial workspace</small><h1>Ticket</h1><p>Kelola tindak lanjut dan phase gate dari lead Qualified. Data account dan peluang tetap bersumber dari Pipeline.</p></div><Link href="/ruang-kawan/pipeline/">Buka Pipeline <FiExternalLink/></Link></header>
  <section className="rk-assignment-stats"><article data-kind="active"><FiClock/><span><strong>{workspace?.tickets.filter(x=>!['closed_won','closed_lost'].includes(x.ticket_status)).length??0}</strong><small>Ticket aktif</small></span></article><article data-kind="review"><FiArrowRight/><span><strong>{workspace?.tickets.filter(x=>x.phase==='handover').length??0}</strong><small>Handover</small></span></article><article data-kind="approved"><FiCheck/><span><strong>{workspace?.tickets.filter(x=>x.phase==='delivery'||x.phase==='report_close').length??0}</strong><small>Delivery & closing</small></span></article></section>
  <div className="rk-ticket-tools"><label><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari ticket, account, atau lead..."/></label><label><FiFilter/><select value={phaseFilter} onChange={e=>setPhaseFilter(e.target.value)}><option value="all">Semua fase</option>{Object.entries(phases).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
  {notice?<p className="rk-work-alert">{notice}</p>:null}{error?<p className="rk-work-alert" data-error>{error}</p>:null}
  <section className="rk-ticket-list">{visible.map(ticket=>{const active=ticket.checklist.filter(x=>x.phase===ticket.phase);const done=active.filter(x=>x.done).length;const overdue=ticket.phase_deadline<new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});return <article key={ticket.id}><button className="rk-ticket-card" onClick={()=>open(ticket)}><header><small>{ticket.ticket_code} · {ticket.lead_code}</small><span data-risk={ticket.ticket_status==='blocked'?'blocked':overdue?'overdue':'track'}>{ticket.ticket_status==='blocked'?'Blocked':overdue?'Overdue':'On Track'}</span></header><h2>{ticket.account_name}</h2><p>{ticket.service_main} · Lead {ticket.stage}</p><div className="rk-ticket-phase"><span>{phases[ticket.phase]}</span><strong>{done}/{active.length} checklist</strong></div><div className="rk-ticket-progress"><i style={{width:`${active.length?done/active.length*100:0}%`}}/></div><footer><span>{ticket.owner_name}</span><time>{formatDate(ticket.phase_deadline)}</time></footer><strong className="rk-ticket-action">Next: {ticket.next_action}</strong></button></article>})}{!visible.length?<div className="rk-work-empty"><FiCheck/><strong>{workspace?.tickets.length?'Tidak ada ticket yang cocok dengan filter':'Belum ada lead Qualified'}</strong><p>Ticket dibuat otomatis ketika lead di Pipeline mencapai stage Qualified.</p><Link href="/ruang-kawan/pipeline/">Lihat Pipeline</Link></div>:null}</section>
 </section>
 {selected?<div className="rk-work-modal"><section className="rk-ticket-detail"><header><div><small>{selected.ticket_code} · {selected.lead_code}</small><h2>{selected.account_name}</h2><p>{selected.service_main} · Status ticket: {statusLabels[selected.ticket_status]??selected.ticket_status}</p></div><button onClick={()=>setSelected(null)}>Tutup</button></header><div className="rk-ticket-stepper">{Object.entries(phases).map(([phase,label])=><span key={phase} data-current={selected.phase===phase} data-complete={Object.keys(phases).indexOf(selected.phase)>Object.keys(phases).indexOf(phase)}>{label}</span>)}</div>
  <div className="rk-ticket-fields"><label>Owner fase<select value={owner} onChange={e=>setOwner(e.target.value)} disabled={!workspace?.can_manage}>{workspace?.members.map(x=><option key={x.id} value={x.id}>{x.name}{x.position?` · ${x.position}`:''}</option>)}</select></label><label>Deadline fase<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} disabled={!workspace?.can_manage}/></label><label className="wide">Next action<input value={action} onChange={e=>setAction(e.target.value)} disabled={!workspace?.can_manage}/></label><label>Deadline next action<input type="date" value={actionDue} onChange={e=>setActionDue(e.target.value)} disabled={!workspace?.can_manage}/></label><label className="wide">Blocker / menunggu client<textarea value={blocker} onChange={e=>setBlocker(e.target.value)} disabled={!workspace?.can_manage} placeholder="Alasan blocker atau konteks menunggu client"/></label></div>
  <section className="rk-ticket-checklist"><h3>Checklist · {phases[selected.phase]}</h3>{selected.checklist.filter(x=>x.phase===selected.phase).map(item=><label key={item.id}><input type="checkbox" checked={item.done} onChange={e=>void toggle(item,e.target.checked)} disabled={!selected.can_contribute}/><span>{item.label}{item.required?<small>Wajib</small>:null}</span></label>)}</section>
  <section className="rk-ticket-members"><h3><FiUsers/> Anggota ticket</h3>{selected.members.map((item,index)=><span key={`${item.membership_id}-${item.member_role}-${index}`}>{item.name} · {item.member_role}</span>)}{workspace?.can_manage?<div><select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Pilih staf...</option>{workspace.members.filter(x=>x.id!==selected.phase_owner_membership_id&&!selected.members.some(m=>m.membership_id===x.id&&m.member_role===memberRole)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={memberRole} onChange={e=>setMemberRole(e.target.value as typeof memberRole)}><option value="assignee">Assignee</option><option value="watcher">Watcher</option><option value="approver">Approver</option></select><button onClick={()=>void addMember()} disabled={!memberId||saving}>Tambahkan</button></div>:null}</section>
  <div className="rk-ticket-integrations"><a href={`/ruang-kawan/pipeline/?lead=${selected.pipeline_lead_id}`}>Lead Pipeline <FiExternalLink/></a>{selected.conversation_id?<Link href={`/ruang-kawan/chat/?conversation=${selected.conversation_id}`}><FiMessageCircle/> Buka Commercial Space</Link>:<span><FiMessageCircle/> Tambahkan assignee/watcher untuk membuat Commercial Space</span>}{selected.project_id?<Link href={`/ruang-kawan/chat/?conversation=${selected.project_conversation_id}`}><FiMessageCircle/> Buka Project Space</Link>:null}{selected.project_id?<Link href="/ruang-kawan/projects/"><FiUsers/> Project {selected.project_code}</Link>:null}</div>
  <footer><button onClick={()=>void save()} disabled={saving||!workspace?.can_manage}>{saving?'Menyimpan...':'Simpan perubahan'}</button>{selected.can_accept_handover?<><select value={projectLead} onChange={e=>setProjectLead(e.target.value)}>{workspace?.members.map(x=><option key={x.id} value={x.id}>Project Lead: {x.name}</option>)}</select><button data-primary onClick={()=>void acceptHandover()} disabled={saving}>{saving?'Mengaktifkan...':'Terima handover & aktifkan Project'}</button></>:nextPhase[selected.phase]&&workspace?.can_transition?<button data-primary onClick={()=>void advance(selected)}>Lanjut ke {phases[nextPhase[selected.phase]!]}</button>:null}</footer>
 </section></div>:null}
 </main>
}
