-- Ruang Kawan: personal 3P + Priority reports, persistent revisions, snapshots and artifact registry.
insert into public.permissions(key,name,description) values
 ('reports.view_self','Lihat report sendiri','Melihat draft, snapshot, dan artifact report pribadi.'),
 ('reports.manage_self','Kelola report sendiri','Membuat dan mengubah report pribadi.'),
 ('reports.configure','Konfigurasi report','Mengatur template output dan konfigurasi generator.')
on conflict(key) do update set name=excluded.name,description=excluded.description;
insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r join public.permissions p on r.key='system_admin' or (r.key in ('executive','project_lead','finance_manager','people_hr_manager','staff','freelancer') and p.key in ('reports.view_self','reports.manage_self')) on conflict do nothing;

create table public.report_templates(id uuid primary key default extensions.gen_random_uuid(),name text not null,artifact_type text not null check(artifact_type in ('document','presentation')),drive_template_url text not null,version integer not null default 1,is_active boolean not null default true,created_by_membership_id uuid not null references public.memberships(id),created_at timestamptz not null default now(),unique(name,artifact_type,version));
create table public.report_drafts(id uuid primary key default extensions.gen_random_uuid(),owner_membership_id uuid not null references public.memberships(id),report_type text not null check(report_type in ('weekly','monthly','custom')),period_start date not null,period_end date not null,status text not null default 'draft' check(status in ('draft','ready','snapshotted','published','superseded')),revision integer not null default 1,score_cache numeric(8,4),last_autosaved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(period_end>=period_start),unique(owner_membership_id,report_type,period_start,period_end,revision));
create table public.report_items(id uuid primary key default extensions.gen_random_uuid(),report_id uuid not null references public.report_drafts(id) on delete cascade,section text not null check(section in ('progress','problem','plan','priority')),text text not null,justification text,source_type text not null check(source_type in ('kpi','activity','pipeline','project','manual')),source_id text,evidence_url text,sort_order integer not null default 100,active boolean not null default true,created_by_membership_id uuid not null references public.memberships(id),updated_by_membership_id uuid not null references public.memberships(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index report_auto_item_unique on public.report_items(report_id,source_type,source_id,section) where source_id is not null and active;
create table public.report_snapshots(id uuid primary key default extensions.gen_random_uuid(),report_id uuid not null references public.report_drafts(id),draft_revision integer not null,owner_membership_id uuid not null references public.memberships(id),report_type text not null,period_start date not null,period_end date not null,score numeric(8,4),summary text,payload_json jsonb not null,checksum text not null,idempotency_key text not null unique,created_by_membership_id uuid not null references public.memberships(id),created_at timestamptz not null default now());
create table public.report_snapshot_kpis(id uuid primary key default extensions.gen_random_uuid(),snapshot_id uuid not null references public.report_snapshots(id) on delete cascade,kpi_result_id uuid,category text,category_weight numeric,target numeric,actual numeric,achievement numeric,status text,source_data jsonb not null default '{}'::jsonb,unique(snapshot_id,kpi_result_id));
create table public.report_artifacts(id uuid primary key default extensions.gen_random_uuid(),snapshot_id uuid not null references public.report_snapshots(id),document_id uuid references public.documents(id),artifact_type text not null check(artifact_type in ('document','presentation')),drive_file_id text,url text,template_version integer,status text not null default 'queued' check(status in ('queued','generating','ready','failed')),idempotency_key text not null unique,generated_at timestamptz,generated_by_membership_id uuid references public.memberships(id),error_message text,created_at timestamptz not null default now());
create table public.report_revision_logs(id bigint generated always as identity primary key,report_id uuid not null references public.report_drafts(id),from_revision integer,to_revision integer,actor_membership_id uuid not null references public.memberships(id),change_summary text,changed_fields_json jsonb,created_at timestamptz not null default now());
create table public.report_usage_events(id bigint generated always as identity primary key,owner_membership_id uuid not null references public.memberships(id),event_name text not null,report_id uuid references public.report_drafts(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index report_drafts_owner_period_idx on public.report_drafts(owner_membership_id,period_start desc);
create index report_items_report_section_idx on public.report_items(report_id,section,sort_order) where active;

create or replace function public.report_period_dates(kind text,start_input date default null,end_input date default null) returns jsonb language plpgsql stable as $$declare today_jkt date:=(now() at time zone 'Asia/Jakarta')::date;s date;e date;begin if kind='weekly' then e:=today_jkt-((extract(isodow from today_jkt)::int));s:=e-6;elsif kind='monthly' then s:=(date_trunc('month',today_jkt)-interval '1 month')::date;e:=(date_trunc('month',today_jkt)-interval '1 day')::date;else s:=start_input;e:=end_input;if s is null or e is null or s>e or e-s>366 then raise exception 'Rentang custom tidak valid atau lebih dari 366 hari.';end if;end if;return jsonb_build_object('start',s,'end',e);end;$$;
create or replace function public.build_report_auto_draft(kind text,start_input date default null,end_input date default null) returns uuid language plpgsql security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();dates jsonb;s date;e date;saved uuid;assignment public.kpi_assignments%rowtype;begin if actor is null or not public.current_user_has_permission('reports.manage_self') then raise exception 'Akses report diperlukan.' using errcode='42501';end if;dates:=public.report_period_dates(kind,start_input,end_input);s:=(dates->>'start')::date;e:=(dates->>'end')::date;select id into saved from public.report_drafts where owner_membership_id=actor and report_type=kind and period_start=s and period_end=e and status in ('draft','ready') order by revision desc limit 1;if saved is not null then return saved;end if;select a.* into assignment from public.kpi_assignments a join public.kpi_periods p on p.id=a.period_id where a.membership_id=actor and p.start_date<=e and p.end_date>=s order by p.start_date desc limit 1;insert into public.report_drafts(owner_membership_id,report_type,period_start,period_end,score_cache) values(actor,kind,s,e,assignment.final_score) returning id into saved;
 insert into public.report_items(report_id,section,text,justification,source_type,source_id,evidence_url,sort_order,created_by_membership_id,updated_by_membership_id)
 select saved,case when a.status='done' then 'progress' when a.status='blocked' or nullif(a.blocker_risk,'') is not null then 'problem' when a.priority in ('high','urgent') then 'priority' else 'plan' end,coalesce(nullif(a.output,''),nullif(a.next_action,''),a.title),case when a.status='blocked' then a.blocker_risk else a.detail end,'activity',a.id::text,a.evidence_url,row_number() over(order by a.activity_date desc)::int*10,actor,actor from public.activities a where a.owner_membership_id=actor and a.activity_date between s and e and (a.status='done' or nullif(a.blocker_risk,'') is not null or nullif(a.next_action,'') is not null or a.priority in ('high','urgent')) on conflict do nothing;
 if assignment.id is not null then insert into public.report_items(report_id,section,text,justification,source_type,source_id,evidence_url,sort_order,created_by_membership_id,updated_by_membership_id)
 select saved,case when coalesce(r.reviewer_score,r.score,0)>=100 then 'progress' when coalesce(r.reviewer_score,r.score,0)<70 then 'problem' else 'priority' end,r.name||' — '||round(coalesce(r.raw_achievement,0),1)||'%',case when coalesce(r.reviewer_score,r.score,0)<70 then 'KPI memerlukan perhatian pada periode ini.' else 'Pencapaian KPI periode.' end,'kpi',r.id::text,r.evidence_url,500+row_number() over(order by coalesce(r.reviewer_score,r.score,0))::int*10,actor,actor from public.kpi_results r where r.assignment_id=assignment.id and r.is_applicable and coalesce(r.reviewer_score,r.score) is not null on conflict do nothing;end if;
 insert into public.report_usage_events(owner_membership_id,event_name,report_id,metadata) values(actor,'draft_created',saved,jsonb_build_object('type',kind,'period_start',s,'period_end',e));return saved;end;$$;
create or replace function public.report_workspace() returns jsonb language plpgsql stable security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();begin if actor is null or not public.current_user_has_permission('reports.view_self') then raise exception 'Akses report diperlukan.' using errcode='42501';end if;return jsonb_build_object('drafts',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'report_type',d.report_type,'period_start',d.period_start,'period_end',d.period_end,'status',d.status,'revision',d.revision,'score_cache',d.score_cache,'last_autosaved_at',d.last_autosaved_at,'updated_at',d.updated_at,'item_count',(select count(*) from public.report_items i where i.report_id=d.id and i.active),'artifact_count',(select count(*) from public.report_snapshots s join public.report_artifacts a on a.snapshot_id=s.id where s.report_id=d.id)) order by d.updated_at desc) from public.report_drafts d where d.owner_membership_id=actor),'[]'::jsonb),'templates',coalesce((select jsonb_agg(to_jsonb(t) order by t.artifact_type,t.version desc) from public.report_templates t where t.is_active),'[]'::jsonb),'usage',jsonb_build_object('published',(select count(*) from public.report_drafts where owner_membership_id=actor and status='published'),'last_90_days',(select count(*) from public.report_usage_events where owner_membership_id=actor and created_at>=now()-interval '90 days')));end;$$;
create or replace function public.get_report_detail(target uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();begin if not exists(select 1 from public.report_drafts where id=target and owner_membership_id=actor) then raise exception 'Report tidak dapat diakses.' using errcode='42501';end if;return jsonb_build_object('report',(select to_jsonb(d) from public.report_drafts d where d.id=target),'items',coalesce((select jsonb_agg(to_jsonb(i) order by case i.section when 'progress' then 1 when 'problem' then 2 when 'plan' then 3 else 4 end,i.sort_order) from public.report_items i where i.report_id=target and i.active),'[]'::jsonb),'snapshots',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'draft_revision',s.draft_revision,'score',s.score,'checksum',s.checksum,'created_at',s.created_at,'artifacts',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at) from public.report_artifacts a where a.snapshot_id=s.id),'[]'::jsonb)) order by s.created_at desc) from public.report_snapshots s where s.report_id=target),'[]'::jsonb));end;$$;
create or replace function public.save_report_item(item_id uuid,payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();saved uuid;target_report uuid:=nullif(payload->>'report_id','')::uuid;begin if not exists(select 1 from public.report_drafts where id=target_report and owner_membership_id=actor and status in ('draft','ready','snapshotted')) then raise exception 'Draft tidak dapat diubah.' using errcode='42501';end if;if item_id is null then insert into public.report_items(report_id,section,text,justification,source_type,source_id,evidence_url,sort_order,created_by_membership_id,updated_by_membership_id) values(target_report,payload->>'section',trim(payload->>'text'),nullif(payload->>'justification',''),coalesce(nullif(payload->>'source_type',''),'manual'),nullif(payload->>'source_id',''),nullif(payload->>'evidence_url',''),coalesce((payload->>'sort_order')::int,100),actor,actor) returning id into saved;else update public.report_items set section=payload->>'section',text=trim(payload->>'text'),justification=nullif(payload->>'justification',''),evidence_url=nullif(payload->>'evidence_url',''),sort_order=coalesce((payload->>'sort_order')::int,sort_order),updated_by_membership_id=actor,updated_at=now() where id=item_id and report_id=target_report returning id into saved;end if;update public.report_drafts set status='ready',revision=revision+1,last_autosaved_at=now(),updated_at=now() where id=target_report;return saved;end;$$;
create or replace function public.delete_report_item(target_item uuid) returns void language plpgsql security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();target_report uuid;begin update public.report_items i set active=false,updated_by_membership_id=actor,updated_at=now() from public.report_drafts d where i.id=target_item and d.id=i.report_id and d.owner_membership_id=actor and d.status in ('draft','ready','snapshotted') returning i.report_id into target_report;if target_report is not null then update public.report_drafts set status='ready',revision=revision+1,last_autosaved_at=now(),updated_at=now() where id=target_report;end if;end;$$;
create or replace function public.snapshot_report(target uuid,idempotency text) returns uuid language plpgsql security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();d public.report_drafts%rowtype;saved uuid;payload jsonb;digest text;begin select * into d from public.report_drafts where id=target and owner_membership_id=actor and status in ('draft','ready','snapshotted');if d.id is null then raise exception 'Report tidak dapat dibekukan.' using errcode='42501';end if;select jsonb_build_object('report',to_jsonb(d),'items',coalesce(jsonb_agg(to_jsonb(i) order by i.section,i.sort_order),'[]'::jsonb)) into payload from public.report_items i where i.report_id=target and i.active;digest:=encode(extensions.digest(payload::text,'sha256'),'hex');insert into public.report_snapshots(report_id,draft_revision,owner_membership_id,report_type,period_start,period_end,score,payload_json,checksum,idempotency_key,created_by_membership_id) values(target,d.revision,actor,d.report_type,d.period_start,d.period_end,d.score_cache,payload,digest,idempotency,actor) on conflict(idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into saved;insert into public.report_snapshot_kpis(snapshot_id,kpi_result_id,category,category_weight,target,actual,achievement,status,source_data) select saved,r.id,r.category_name,r.category_weight,r.target_value,r.actual_value,r.raw_achievement,case when coalesce(r.reviewer_score,r.score)>=100 then 'Exceeded' when coalesce(r.reviewer_score,r.score)>=80 then 'On Track' when coalesce(r.reviewer_score,r.score)>=70 then 'Needs Attention' else 'At Risk' end,to_jsonb(r) from public.kpi_assignments a join public.kpi_periods p on p.id=a.period_id join public.kpi_results r on r.assignment_id=a.id where a.membership_id=actor and p.start_date<=d.period_end and p.end_date>=d.period_start on conflict do nothing;update public.report_drafts set status='snapshotted',updated_at=now() where id=target;insert into public.report_usage_events(owner_membership_id,event_name,report_id,metadata) values(actor,'snapshot_created',target,jsonb_build_object('snapshot_id',saved));return saved;end;$$;
create or replace function public.register_report_artifact(target_snapshot uuid,kind text,url_value text,status_value text default 'ready') returns uuid language plpgsql security definer set search_path=public as $$declare actor uuid:=public.current_membership_id();s public.report_snapshots%rowtype;saved uuid;doc uuid;key text;begin select * into s from public.report_snapshots where id=target_snapshot and owner_membership_id=actor;if s.id is null then raise exception 'Snapshot tidak dapat diakses.' using errcode='42501';end if;key:=s.id::text||':'||kind;insert into public.report_artifacts(snapshot_id,artifact_type,url,status,idempotency_key,generated_at,generated_by_membership_id) values(s.id,kind,url_value,status_value,key,case when status_value='ready' then now() end,actor) on conflict(idempotency_key) do update set url=excluded.url,status=excluded.status,generated_at=excluded.generated_at,generated_by_membership_id=excluded.generated_by_membership_id returning id into saved;if status_value='ready' and nullif(url_value,'') is not null then insert into public.documents(document_id,title,document_type,category,owner_membership_id,source_module,linked_record_id,linked_record_name,status,classification,valid_from,created_by_membership_id,updated_by_membership_id) values('DOC-RPT-'||substr(replace(s.id::text,'-',''),1,12)||'-'||upper(substr(kind,1,3)),'Campus Innovate - '||initcap(s.report_type)||' 3P+Priority - '||s.period_start||' to '||s.period_end,case when kind='document' then 'KPI Report' else 'KPI Presentation' end,'Reports',actor,'reports',s.id::text,'Report Snapshot','effective','internal',s.period_start,actor,actor) on conflict(document_id) do update set updated_at=now() returning id into doc;insert into public.document_versions(document_id,version_number,file_name,drive_file_url,source_kind,revision_summary,immutable_at,created_by_membership_id) values(doc,1,'Campus Innovate Report',url_value,'generated','Generated from immutable report snapshot',now(),actor) on conflict(document_id,version_number) do update set drive_file_url=excluded.drive_file_url;update public.report_artifacts set document_id=doc where id=saved;update public.report_drafts set status='published',updated_at=now() where id=s.report_id;end if;insert into public.report_usage_events(owner_membership_id,event_name,report_id,metadata) values(actor,'artifact_registered',s.report_id,jsonb_build_object('artifact_type',kind,'status',status_value));return saved;end;$$;

-- Aggregate adoption signals only; report content remains personal. Use after real usage exists
-- to decide whether a separate consolidated-report product is justified.
create or replace function public.report_adoption_metrics(days_back integer default 90) returns jsonb language plpgsql stable security definer set search_path=public as $$declare since_at timestamptz:=now()-make_interval(days=>greatest(1,least(days_back,365)));begin if not public.current_user_has_permission('reports.configure') then raise exception 'Akses konfigurasi report diperlukan.' using errcode='42501';end if;return jsonb_build_object(
 'window_days',greatest(1,least(days_back,365)),
 'eligible_members',(select count(distinct m.id) from public.memberships m where m.status='active' and (exists(select 1 from public.member_permission_overrides o join public.permissions p on p.id=o.permission_id where o.membership_id=m.id and p.key='reports.manage_self' and o.effect='allow') or (not exists(select 1 from public.member_permission_overrides o join public.permissions p on p.id=o.permission_id where o.membership_id=m.id and p.key='reports.manage_self' and o.effect='deny') and exists(select 1 from public.member_roles mr join public.role_permissions rp on rp.role_id=mr.role_id join public.permissions p on p.id=rp.permission_id where mr.membership_id=m.id and p.key='reports.manage_self')))),
 'active_reporters',(select count(distinct owner_membership_id) from public.report_drafts where created_at>=since_at),
 'repeat_reporters',(select count(*) from (select owner_membership_id from public.report_drafts where created_at>=since_at group by owner_membership_id having count(distinct (report_type,period_start,period_end))>=2) q),
 'drafts',(select count(*) from public.report_drafts where created_at>=since_at),
 'snapshots',(select count(*) from public.report_snapshots where created_at>=since_at),
 'ready_artifacts',(select count(*) from public.report_artifacts where status='ready' and created_at>=since_at),
 'linked_documents',(select count(*) from public.report_artifacts where document_id is not null and created_at>=since_at));end;$$;

alter table public.report_templates enable row level security;alter table public.report_drafts enable row level security;alter table public.report_items enable row level security;alter table public.report_snapshots enable row level security;alter table public.report_snapshot_kpis enable row level security;alter table public.report_artifacts enable row level security;alter table public.report_revision_logs enable row level security;alter table public.report_usage_events enable row level security;
revoke all on public.report_templates,public.report_drafts,public.report_items,public.report_snapshots,public.report_snapshot_kpis,public.report_artifacts,public.report_revision_logs,public.report_usage_events from anon,authenticated;
grant execute on function public.report_period_dates(text,date,date),public.build_report_auto_draft(text,date,date),public.report_workspace(),public.get_report_detail(uuid),public.save_report_item(uuid,jsonb),public.delete_report_item(uuid),public.snapshot_report(uuid,text),public.register_report_artifact(uuid,text,text,text),public.report_adoption_metrics(integer) to authenticated;
revoke execute on function public.report_period_dates(text,date,date),public.build_report_auto_draft(text,date,date),public.report_workspace(),public.get_report_detail(uuid),public.save_report_item(uuid,jsonb),public.delete_report_item(uuid),public.snapshot_report(uuid,text),public.register_report_artifact(uuid,text,text,text),public.report_adoption_metrics(integer) from anon,public;
