create table if not exists public.noortura_sheet_export_tokens (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  label text not null default 'Noortura Google Sheet',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  constraint noortura_sheet_export_token_hash_format
    check (token_hash ~ '^[0-9a-f]{64}$')
);

alter table public.noortura_sheet_export_tokens enable row level security;
revoke all on table public.noortura_sheet_export_tokens from public, anon, authenticated;
grant select, update on table public.noortura_sheet_export_tokens to service_role;

insert into public.noortura_sheet_export_tokens (token_hash, label, is_active)
values ('ef5fee5a2d84228da37f21421d116aeafa7a9ff949bf4e9bcd7fbb63ffbb2708', 'Noortura Open House 2026 Google Sheet pull sync', true)
on conflict (token_hash) do update
set label = excluded.label,
    is_active = true;

update public.noortura_open_house_rsvps
set sheet_sync_status = 'pending',
    sheet_synced_at = null,
    sheet_sync_error = null
where event_code = 'NOORTURA_OH_2026'
  and sheet_sync_status in ('failed', 'disabled');
